// Тексты локали «fr». Структура зеркальна остальным локалям.
import { FACTS } from "../facts";

export const ui = {
  title: "MediaChef — convertisseur vidéo et audio hors ligne avec transcription",
  description:
    "Application gratuite et open source pour macOS, Windows et Linux : convertissez vidéo et audio sur votre propre ordinateur et transformez la parole en texte avec Whisper. Sans téléversement, sans limite de taille, sans abonnement.",
  nav: { recipes: "Recettes", transcribe: "Transcription", privacy: "Hors ligne", faq: "Questions" },
  skipToContent: "Aller au contenu",
  heroTitle1: "N'importe quel fichier, vers n'importe quel format.",
  heroTitle2: "La parole, en texte.",
  heroAccent: "Tout sur votre ordinateur.",
  heroSub:
    "MediaChef est une application gratuite qui transforme FFmpeg et Whisper en fiches recettes : convertissez vidéo et audio, extrayez le son d'un clip, passez un enregistrement en texte — hors ligne, sur votre machine, sans rien envoyer nulle part.",
  trust: [
    `Version ${FACTS.version}`,
    `${FACTS.recipeCount} recettes intégrées`,
    `${FACTS.modelCount} modèles Whisper`,
    "macOS · Windows · Linux",
    "Open source · GPL-3.0",
  ],
  ctaMac: "Télécharger pour macOS",
  ctaWin: "Télécharger pour Windows",
  ctaLinux: "Télécharger pour Linux",
  ctaNote: "Gratuit et open source —",
  ctaNoteLink: "voir le code sur GitHub",
  howTitle: "Comment ça marche",
  steps: [
    { n: "1", h: "Déposez un fichier", p: "Glissez une vidéo ou un enregistrement. MediaChef analyse le fichier et n'affiche que les recettes qui correspondent à ce qu'il y a trouvé." },
    { n: "2", h: "Choisissez une recette", p: "Chaque action est une fiche simple : « Extraire l'audio en MP3 », « Créer des sous-titres SRT pour une vidéo », « Compresser la vidéo ». Les valeurs par défaut sont déjà pertinentes et l'aperçu montre la commande FFmpeg exacte." },
    { n: "3", h: "Récupérez le résultat", p: "Le fichier apparaît à côté de l'original — ou dans le dossier de votre choix. La file affiche la progression, le temps restant et l'endroit où le résultat a atterri." },
  ],
  shotAlt:
    "Écran principal de MediaChef : menu latéral avec Conversion, Modèles et Réglages, une zone de dépôt de fichiers et la file des tâches à droite.",
  shotCaption:
    "La vraie fenêtre, dans le thème où vous lisez en ce moment. La zone de dépôt au centre, la file à droite, les moteurs déjà à l'intérieur.",
  outTitle: "Ce qu'il fait dès l'installation",
  outLead:
    "L'application embarque dix-sept recettes. Chacune est une véritable tâche FFmpeg ou Whisper dont les paramètres sont déjà renseignés, et chacune écrit son résultat à côté de votre fichier sous la forme {nom}.{quoi}.{extension}.",
  outHead: ["Sens", "Recette dans l'application", "Ce que vous obtenez"],
  outRows: [
    ["Vidéo → audio", "Extraire l'audio en MP3", "<code>clip.audio.mp3</code> en 128, 192 ou 320 kbps"],
    ["Vidéo → sous-titres", "Créer des sous-titres SRT", "<code>clip.subs.srt</code> avec les minutages"],
    ["Audio → texte", "Transcrire l'audio en texte", "<code>talk.transcript.txt</code>, texte brut"],
    ["Toute langue → anglais", "Traduire la parole en texte anglais", "<code>talk.english.txt</code> en une seule passe"],
    ["MP4 → MKV", "Convertir MP4 en MKV", "Réempaqueté, pas réencodé — quelques secondes, sans perte"],
    ["Vidéo → plus léger", "Compresser la vidéo (préréglage de qualité)", "H.264 en CRF 23, 28 ou 33"],
    ["Vidéo → GIF", "Vidéo en GIF", "10–24 i/s, largeur 320–640"],
    ["Tout le reste", "Commande FFmpeg personnalisée", "Vos propres arguments, avec l'aperçu de la commande"],
  ],
  modelsTitle: "Modèles Whisper",
  modelsLead:
    "La transcription s'appuie sur whisper.cpp et les modèles Whisper d'OpenAI. Vous téléchargez un modèle une fois depuis l'écran Modèles ; ensuite tout fonctionne réseau coupé. Modèle plus gros, meilleur texte, calcul plus long.",
  modelsHead: ["Modèle", "Téléchargement", "À quoi il sert"],
  modelSizes: {
    tiny: "78 Mo",
    base: "148 Mo",
    small: "488 Mo",
    "large-v3-turbo": "1,62 Go",
  },
  modelNotes: {
    tiny: "Le plus rapide, qualité approximative. Un brouillon de parole claire en une fraction du temps.",
    base: "Rapide, qualité correcte. Suffisant pour retrouver dans un enregistrement le passage qui vous intéresse.",
    small: "L'équilibre recommandé — la valeur par défaut de toutes les recettes de transcription.",
    "large-v3-turbo": "La meilleure qualité, optimisé pour Apple Silicon. Pour un texte destiné à être publié.",
  },
  defaultTag: "par défaut",
  recipesTitle: "Des recettes plutôt que des commandes",
  recipesLead:
    "FFmpeg sait presque tout faire — dans la langue du terminal. MediaChef traduit : vous choisissez quoi faire, les paramètres sont déjà réglés. L'aperçu montre la vraie commande, et vous apprenez au passage.",
  recipes: [
    { tile: "tile-ochre", h: "Extraire l'audio en MP3", p: "Sortez la bande-son de n'importe quelle vidéo." },
    { tile: "tile-green", h: "Créer des sous-titres SRT", p: "Whisper écoute et écrit un fichier SRT." },
    { tile: "tile-green", h: "Compresser la vidéo", p: "Faites tenir un clip dans la taille acceptée par la messagerie." },
    { tile: "tile-purple", h: "Vidéo en GIF", p: "Un GIF net en boucle, de 10 à 24 i/s." },
    { tile: "tile-green", h: "Transcrire l'audio en texte", p: "Une réunion ou un mémo vocal en texte brut." },
    { tile: "tile-blue", h: "Traduire la parole en anglais", p: "Whisper transcrit et traduit en une seule passe." },
    { tile: "tile-blue", h: "Convertir MP4 en MKV", p: "Réempaquetage sans réencodage — instantané." },
    { tile: "tile-red", h: "Supprimer le son d'une vidéo", p: "Retirez toutes les pistes audio et gardez l'image." },
  ],
  trTitle: "Transcrivez l'audio en texte sans quitter votre machine",
  trBullets: [
    { h: "Whisper, exécuté en local.", p: "Le modèle vocal d'OpenAI tourne sur votre propre processeur via whisper.cpp — les enregistrements ne quittent jamais la machine." },
    { h: "Modèles téléchargés dans l'app.", p: "De tiny, 78 Mo, à large-v3-turbo, 1,62 Go — choisissez selon la tâche depuis l'écran Modèles." },
    { h: "Texte ou sous-titres.", p: "TXT brut, SRT et VTT avec minutages, ou JSON avec le temps de chaque segment pour vos outils." },
    { h: "Un résultat honnête.", p: "Si un fichier ne contient pas de parole, MediaChef le dit : « Aucune parole détectée » — il ne livre jamais un fichier vide coché en vert." },
  ],
  recipesLink: "Guide complet : convertir MP4 en MP3 →",
  catalogLink: `Les ${FACTS.recipeCount} recettes, par catégorie →`,
  trLink: "Guide complet : transcrire l'audio en texte →",
  privTitle: "Vos fichiers ne partent nulle part",
  privLead:
    "Un convertisseur en ligne vous demande d'envoyer le fichier sur le serveur de quelqu'un d'autre, d'attendre dans une file et de faire confiance à sa politique de conservation. MediaChef travaille sur votre processeur : un gigaoctet de capture d'écran et l'audio privé d'une réunion se convertissent de la même façon — le Wi-Fi coupé.",
  privChips: ["Aucun téléversement", "Aucune limite de taille", "Aucun abonnement"],
  ossTitle: "Open source, moteurs inclus",
  ossLead:
    "GPL-3.0, avec tout l'historique de développement public sur GitHub. Depuis la 0.4.0, chaque téléchargement embarque ses propres moteurs — rien à installer dans le PATH, rien à configurer.",
  engineRows: [
    { k: `FFmpeg ${FACTS.ffmpeg}`, v: "conversion · GPL v3" },
    { k: `whisper.cpp ${FACTS.whisper}`, v: "reconnaissance vocale · MIT" },
    { k: "macOS · Windows · Linux", v: "dmg ~66 Mo · installeur ~82 Mo · AppImage ~181 Mo · deb ~118 Mo" },
  ],
  ossNotice: "Versions et licences exactes de tout ce qui est embarqué — NOTICE.md",
  faqTitle: "Questions fréquentes",
  faq: [
    { q: "C'est vraiment gratuit ?", a: "Oui. MediaChef est open source sous GPL-3.0 — sans compte, sans période d'essai, sans filigrane. Le convertisseur et la transcription constituent toute l'application, et le code est public sur GitHub." },
    { q: "Quels formats sont pris en charge ?", a: "Tout ce que FFmpeg sait lire : MP4, MKV, MOV, WebM, AVI, TS, MP3, WAV, FLAC, M4A, OGG et des dizaines d'autres. MediaChef analyse le fichier avec ffprobe au lieu de se fier à son extension, donc les recettes affichées sont celles qui conviennent réellement." },
    { q: "Où mes fichiers sont-ils envoyés ?", a: "Nulle part. La conversion et la transcription s'exécutent entièrement sur votre ordinateur. La seule chose que MediaChef télécharge est un modèle Whisper — une fois, depuis l'écran Modèles." },
    { q: "Quelle est la précision de la transcription ?", a: "Elle utilise les modèles Whisper d'OpenAI via whisper.cpp v1.7.6. La précision suit le modèle choisi : tiny est instantané et approximatif, small est l'équilibre par défaut, large-v3-turbo frôle le niveau humain sur une parole claire. La langue est détectée automatiquement." },
    { q: "Est-ce que ça marche hors ligne ?", a: "Oui. FFmpeg et Whisper sont inclus dans le téléchargement : la conversion fonctionne hors ligne dès le premier lancement, et la transcription aussi une fois le modèle récupéré." },
    { q: "Pourquoi ne pas utiliser un convertisseur en ligne ?", a: "Pour un petit fichier public, un convertisseur en ligne fait l'affaire. Les enregistrements privés, les vidéos de plusieurs gigaoctets, les lots et tout ce qui relève d'un accord de confidentialité se traitent mieux en local : pas d'attente de téléversement, pas de plafond de taille, et rien qui traîne sur le disque d'un tiers." },
  ],
  finalTitle: "Mettez un chef aux commandes de vos fichiers",
  finalSub: `Gratuit, open source, ${FACTS.platformCount} plateformes. Version ${FACTS.version}.`,
  betaNote:
    "MediaChef est jeune : les binaires ne sont pas encore signés par Apple ni Microsoft, le premier lancement demande donc une confirmation — une notice en texte brut accompagne chaque téléchargement.",
  footRights: "© 2026 mediachef.app · GPL-3.0",
  footTagline: "Une cuisine média open source.",
  tocLabel: "Sur cette page",
  breadcrumbHome: "Accueil",
  alsoLabel: "À lire ensuite",
  footNavLabel: "Liens du projet",

  menu: {
    navLabel: "Site",
    menu: "Menu",
    features: "Fonctions",
    guides: "Guides",
    download: "Télécharger",
    faq: "Questions",
    gConvert: "Conversion",
    gTranscribe: "Transcription",
    gTrust: "Confidentialité et code",
    gMac: "macOS",
    gWin: "Windows",
    gLinux: "Linux",
    allFiles: "Tous les fichiers et les notes de version",
    footProduct: "Produit",
    footGuides: "Guides",
    footDownload: "Télécharger",
    footProject: "Projet",
    footBlurb: `Une cuisine média gratuite pour macOS, Windows et Linux. FFmpeg ${FACTS.ffmpeg} et whisper.cpp ${FACTS.whisper} sont inclus dans le téléchargement — rien à installer à part.`,
    license: "Licence GPL-3.0",
    notice: "Ce qui est embarqué — NOTICE.md",
    sourceCode: "Code source sur GitHub",
    feedback: "Signaler un problème ou demander une fonction",
    releases: "Toutes les versions",
    langLabel: "Langue",
    // Подпись на схеме окна приложения в hero.
    dropHere: "Déposez les fichiers ici",
    dlWin: "Windows · installeur",
    nApple: "Apple Silicon",
    nZip: "Apple Silicon, sans installeur",
    nWin: "64 bits",
    nAppimage: "x86_64, s'exécute tel quel",
    nDeb: "x86_64, Debian et Ubuntu",
    sHow: "Comment ça marche",
    sRecipes: "Recettes",
    sOut: "Ce qu'il fait dès l'installation",
    sTranscribe: "Transcription",
    sModels: "Modèles Whisper",
    sPrivacy: "Hors ligne et privé",
    sOss: "Open source",
    sFaq: "Questions",
    pMp3: "MP4 en MP3",
    pTranscribe: "Audio en texte",
  },
};

export const landings = {
  mp3: {
    title: "Convertir MP4 en MP3 gratuitement et hors ligne — MediaChef",
    description:
      "Extrayez l'audio d'un MP4 et enregistrez-le en MP3 sur votre propre ordinateur : sans téléversement, sans plafond de taille, sans filigrane. Application gratuite et open source pour macOS, Windows et Linux.",
    h1: "Convertir MP4 en MP3 — gratuit, hors ligne, sur votre ordinateur",
    crumb: "MP4 en MP3",
    lead:
      "MediaChef embarque une recette appelée « Extraire l'audio en MP3 ». Déposez une vidéo, choisissez un débit, lancez : la bande-son est écrite à côté de l'original en MP3. Le fichier ne quitte jamais votre machine, il n'y a pas de limite de taille, et tout fonctionne réseau coupé.",
    sections: { how: "how", table: "bitrate", why: "offline", faq: "faq" },
    toc: ["Comment convertir MP4 en MP3", "Quel débit choisir", "Pourquoi convertir sur votre ordinateur", "Questions"],
    stepsTitle: "Comment convertir MP4 en MP3",
    steps: [
      { h: "Téléchargez MediaChef", p: "Un fichier pour macOS, Windows ou Linux. FFmpeg est déjà à l'intérieur — rien à installer à part, rien à ajouter au PATH." },
      { h: "Déposez le MP4", p: "MediaChef lit le fichier avec ffprobe et ne garde que les recettes adaptées. Une vidéo avec piste audio reçoit immédiatement la fiche MP3." },
      { h: "Choisissez « Extraire l'audio en MP3 »", p: "Sélectionnez le débit : 128k pour la parole, 192k par défaut, 320k pour l'archivage. L'aperçu de la commande se met à jour à chaque changement." },
      { h: "Lancez et récupérez le fichier", p: "Le MP3 apparaît à côté de la vidéo sous le nom clip.audio.mp3. La file affiche la progression, le temps restant et le chemin final." },
    ],
    shotAlt:
      "MediaChef prêt à convertir MP4 en MP3 : la zone de dépôt attend un fichier vidéo, la file des tâches est à droite.",
    shotCaption: "La zone où va le MP4. Les recettes apparaissent dès que MediaChef a lu le fichier.",
    tableTitle: "Quel débit choisir",
    tableLead:
      "La recette propose trois débits. Les tailles ci-dessous valent pour une heure d'audio — c'est de l'arithmétique à partir du débit, donc un enregistrement de deux heures pèse simplement le double.",
    tableHead: ["Débit", "Une heure d'audio", "À choisir quand"],
    tableRows: [
      ["128 kbps", "≈ 58 Mo", "Parole : entretiens, podcasts, cours, mémos vocaux. Le fichier le plus léger, sans perte audible sur une voix."],
      ["192 kbps", "≈ 86 Mo", "La valeur par défaut. La musique que vous écoutez vraiment, et tout ce dont vous n'êtes pas sûr."],
      ["320 kbps", "≈ 144 Mo", "L'archivage, ou un audio que vous allez encore monter et réencoder plus tard."],
    ],
    tableNote:
      "Pas seulement le MP4 : la même recette apparaît pour MKV, MOV, WebM, AVI, TS et tout ce que FFmpeg sait lire, du moment que le fichier a une piste audio.",
    whyTitle: "Pourquoi convertir sur votre ordinateur",
    whyBullets: [
      { h: "Rien n'est envoyé.", p: "Un appel enregistré ou un montage non publié reste sur votre disque. Il n'existe aucune copie serveur dont il faudrait croire la politique de conservation." },
      { h: "Aucun plafond de taille.", p: "Les convertisseurs en ligne s'arrêtent entre 100 Mo et 2 Go et vous mettent dans une file. Une capture d'écran de quatre gigaoctets se convertit comme une de quatre mégaoctets." },
      { h: "Plus rapide sur de vrais fichiers.", p: "Extraire une piste audio déjà présente est rapide. Le lent, c'est d'envoyer la vidéo d'abord — et en local cette étape n'existe pas." },
      { h: "Gratuit, sans compte.", p: "Open source GPL-3.0 : sans inscription, sans essai, sans filigrane, sans limite par fichier." },
      { h: "Par lots, pas un par un.", p: "Déposez tous les clips d'un coup ; la file les traite et vous indique où chaque MP3 a atterri." },
    ],
    faqTitle: "Questions fréquentes",
    faq: [
      { q: "Convertir MP4 en MP3 fait-il perdre en qualité ?", a: "Le MP3 est un format avec perte, la piste est donc réencodée une fois. Aux 192 kbps par défaut, c'est inaudible sur de la parole et très proche de l'inaudible sur de la musique. Si le fichier est un master que vous allez retravailler, prenez 320 kbps." },
      { q: "Quelle est la taille maximale d'un fichier ?", a: "MediaChef n'impose aucune limite — la limite, c'est votre espace disque libre, et l'application le vérifie avant de démarrer. La durée n'entre pas en compte non plus : un enregistrement de trois heures est une seule tâche dans la file." },
      { q: "Est-ce que ça marche sans internet ?", a: "Oui, totalement. FFmpeg est inclus dans le téléchargement, la conversion ne touche donc jamais au réseau. Seule la transcription nécessite de récupérer un modèle une fois." },
      { q: "Puis-je convertir plusieurs vidéos à la fois ?", a: "Oui. Déposez-les toutes, ajoutez la recette, et la file les enchaîne avec progression et temps restant pour chacune." },
      { q: "Y a-t-il un filigrane ou une offre payante ?", a: "Non. MediaChef est open source GPL-3.0 sans aucune offre payante, et ne touche pas à votre audio au-delà de la conversion demandée." },
      { q: "Si je transforme un MP4 en MP3, la vidéo d’origine reste-t-elle ?", a: "Oui. MediaChef lit la vidéo et écrit un nouveau MP3 à côté : le MP4 n’est ni écrasé, ni renommé, ni supprimé, vous pouvez donc en extraire le son autant de fois que nécessaire. Rien n’est envoyé non plus, tout tourne sans connexion." },
    ],
    ctaTitle: "Sortez le MP3 de cette vidéo",
    ctaSub: `MediaChef ${FACTS.version} — gratuit, open source, macOS · Windows · Linux.`,
    also: [
      { page: "catalog", label: "Le catalogue complet des recettes, par catégorie" },
      { page: "transcribe", label: "Transcrire l'audio en texte — hors ligne, avec Whisper" },
      { page: "home", label: `Les ${FACTS.recipeCount} recettes et le fonctionnement de MediaChef` },
    ],
  },
  transcribe: {
    title: "Transcrire l'audio en texte hors ligne avec Whisper — MediaChef",
    description:
      "Transformez des enregistrements en texte sur votre propre ordinateur avec Whisper : TXT, SRT, VTT ou JSON. Sans téléversement, sans facturation à la minute, sans limite de durée. Application gratuite pour macOS, Windows et Linux.",
    h1: "Transcrire l'audio en texte — hors ligne, sur votre ordinateur",
    crumb: "Audio en texte",
    lead:
      "MediaChef exécute Whisper d'OpenAI en local via whisper.cpp. Téléchargez un modèle une fois, déposez un enregistrement ou une vidéo, puis choisissez ce que vous voulez en sortie : texte brut, sous-titres SRT ou VTT minutés, ou JSON avec le temps de chaque segment. L'audio n'est jamais envoyé, et il n'y a pas de prix à la minute.",
    sections: { how: "how", table: "models", why: "offline", faq: "faq" },
    toc: ["Comment transcrire un enregistrement", "Quel modèle Whisper choisir", "Pourquoi transcrire sur votre ordinateur", "Questions"],
    outLabel: "Ce que vous obtenez",
    outSample: "00:00:04  Bonjour à tous, on commence…\n00:00:11  Premier point : les plans du trimestre.\n00:00:19  Il y a trois scénarios, je montre le tableau.",
    outNote: "TXT sans minutages, SRT et VTT avec, JSON avec le début et la fin de chaque segment.",
    stepsTitle: "Comment transcrire un enregistrement",
    steps: [
      { h: "Téléchargez MediaChef", p: "Un fichier pour macOS, Windows ou Linux. whisper.cpp v1.7.6 est déjà inclus ; seul le modèle se télécharge à part." },
      { h: "Choisissez un modèle Whisper", p: "Ouvrez Modèles et téléchargez-en un — small (488 Mo) est l'équilibre par défaut. Un seul téléchargement ; ensuite la transcription fonctionne réseau coupé." },
      { h: "Déposez l'enregistrement ou la vidéo", p: "Audio et vidéo passent tous les deux : MediaChef extrait lui-même le son d'une vidéo, l'enregistrement d'une réunion et un MP4 suivent donc le même chemin." },
      { h: "Choisissez la sortie voulue", p: "« Transcrire l'audio en texte » pour du TXT, « Transcrire l'audio en sous-titres SRT » ou « Transcrire l'audio en WebVTT » pour des sous-titres minutés, « Transcrire l'audio en JSON avec minutages » pour l'outillage." },
      { h: "Lancez et lisez le résultat", p: "Le texte atterrit à côté du fichier sous le nom talk.transcript.txt. La file affiche la progression ; s'il n'y a pas de parole dans le fichier, MediaChef le dit au lieu d'en écrire un vide." },
    ],
    shotAlt:
      "MediaChef avant la transcription : la zone de dépôt d'un enregistrement, avec Modèles dans le menu latéral d'où se téléchargent les modèles Whisper.",
    shotCaption: "Les modèles vivent dans le menu latéral — un téléchargement, puis la transcription se fait hors ligne.",
    tableTitle: "Quel modèle Whisper choisir",
    tableLead:
      "Le catalogue propose quatre modèles, téléchargés depuis l'application. Plus gros signifie meilleur texte et calcul plus long sur la même machine : choisissez selon la tâche plutôt qu'une fois pour toutes.",
    tableHead: ["Modèle", "Téléchargement", "Quand le choisir"],
    tableRows: [
      ["tiny", "78 Mo", "Une première passe sur une parole claire, ou quand il s'agit juste de repérer où commence un sujet."],
      ["base", "148 Mo", "Des notes pour vous : un texte lisible que vous relirez et corrigerez de toute façon."],
      ["small", "488 Mo", "La valeur par défaut de toutes les recettes de transcription, et celle que la plupart gardent. Entretiens, réunions, cours."],
      ["large-v3-turbo", "1,62 Go", "Un texte destiné à quelqu'un d'autre : sous-titres publiés, citations reprises. Optimisé pour Apple Silicon."],
    ],
    tableNote:
      "La langue est détectée automatiquement, et vous pouvez aussi la fixer. Deux recettes supplémentaires traduisent n'importe quelle langue vers l'anglais — en texte ou en sous-titres minutés — dans la même passe.",
    whyTitle: "Pourquoi transcrire sur votre ordinateur",
    whyBullets: [
      { h: "L'audio confidentiel le reste.", p: "Entretiens, notes cliniques, appels juridiques, tout ce qui relève d'un accord de confidentialité : le fichier est lu par un processus de votre machine et par rien d'autre." },
      { h: "Pas de facturation à la minute.", p: "La transcription dans le cloud se facture à la minute. En local, la dixième heure d'audio coûte ce qu'a coûté la première : rien." },
      { h: "Aucune limite de durée ni de taille.", p: "Un enregistrement de quatre heures est une tâche dans la file, pas une offre payante ni un bricolage de découpage de fichier." },
      { h: "Fonctionne sans aucun réseau.", p: "Une fois le modèle sur le disque, la transcription est hors ligne : dans un avion, dans un laboratoire, sur une machine isolée." },
      { h: "Sous-titres et texte d'une même passe.", p: "SRT et VTT portent les minutages pour un lecteur, TXT est de la prose propre, JSON contient les temps des segments pour vos propres scripts." },
    ],
    faqTitle: "Questions fréquentes",
    faq: [
      { q: "Quelle est la précision de Whisper ?", a: "La précision suit le modèle : tiny est un brouillon, small est l'équilibre par défaut, large-v3-turbo frôle le niveau humain sur une parole claire. Un audio propre à un seul locuteur donne les meilleurs résultats ; les accents marqués, les gens qui parlent en même temps et la musique sous la voix coûtent en précision — comme pour n'importe quel système de reconnaissance vocale." },
      { q: "Quelles langues sont gérées ?", a: "Whisper couvre une centaine de langues et détecte la langue tout seul ; vous pouvez aussi la fixer si la détection se trompe. Deux recettes traduisent la parole depuis n'importe laquelle vers l'anglais en une passe, en texte ou en sous-titres SRT." },
      { q: "Dans quels formats sort la transcription ?", a: "TXT pour du texte brut, SRT et VTT avec minutages pour les lecteurs et les logiciels de montage, et JSON avec le début et la fin de chaque segment pour les scripts et l'outillage." },
      { q: "Faut-il internet ?", a: "Une fois, pour télécharger un modèle Whisper depuis l'écran Modèles — de 78 Mo à 1,62 Go selon celui que vous prenez. Ensuite la transcription tourne entièrement hors ligne." },
      { q: "Et si l'enregistrement ne contient pas de parole ?", a: "MediaChef signale « Aucune parole détectée » au lieu d'écrire un fichier vide et de cocher la tâche en vert. Le silence, la musique sans voix et un fichier choisi par erreur se terminent de la même façon honnête." },
      { q: "Puis-je transformer une vidéo en texte, ou seulement de l’audio ?", a: "La vidéo fonctionne pareil. MediaChef récupère le son directement dans le fichier : un MP4, un MKV ou un MOV part droit à la transcription, et il existe même une recette « Récupérer le texte d’une vidéo ». Inutile de le changer en audio d’abord." },
    ],
    ctaTitle: "Transformez cet enregistrement en texte",
    ctaSub: `MediaChef ${FACTS.version} — Whisper en local, gratuit et open source.`,
    also: [
      { page: "catalog", label: "Le catalogue complet des recettes, par catégorie" },
      { page: "mp3", label: "Convertir MP4 en MP3 — gratuit et hors ligne" },
      { page: "home", label: `Les ${FACTS.recipeCount} recettes et le fonctionnement de MediaChef` },
    ],
  },
};

/** Каталог рецептов: /<locale>/<slug>/. Названия рецептов, описания и алиасы
 *  берутся из recipes/*.yaml — здесь только обвязка страницы. */
export const catalog = {
  title: `Les ${FACTS.recipeCount} recettes de MediaChef — vidéo, audio et transcription`,
  description: "Toutes les recettes livrées avec MediaChef : convertir vidéo et audio, compresser, découper, redimensionner, récupérer le son, faire un GIF, transcrire la parole en texte avec Whisper. Gratuit, open source, fonctionne sans connexion sur macOS, Windows et Linux.",
  h1: `Les ${FACTS.recipeCount} recettes`,
  crumb: "Recettes",
  lead: "MediaChef ne vous demande pas d'apprendre des options. Chaque tâche est une fiche : déposez le fichier, choisissez la fiche, lancez. Voici le catalogue complet tel qu'il est livré — ce que chaque recette accepte, ce qu'elle rend, et ce que vous pouvez taper dans la recherche de l'application pour la trouver.",
  // Разделы страницы. Категории из YAML сведены в них по смыслу
  // результата — см. BUCKET в recipes.ts.
  sections: {
    speech: "Parole, texte et sous-titres",
    video: "Vidéo",
    audio: "Audio",
    advanced: "Avancé",
  },
  // Названия категорий совпадают с теми, что человек увидит в самом приложении.
  cats: {
    "extract": "Extraire",
    "transcribe": "Transcrire",
    "convert-video": "Convertir la vidéo",
    "convert-audio": "Convertir l'audio",
    "compress": "Compresser",
    "cut": "Découper",
    "geometry": "Taille",
    "gif": "GIF",
    "audio-in-video": "Son de la vidéo",
    "advanced": "Avancé",
  },
  accepts: "Accepte",
  produces: "Rend",
  settings: "Réglages",
  searchAs: "Se trouve aussi par",
  types: { video: "vidéo", audio: "audio", any: "n'importe quel fichier" },
  noParams: "Rien à régler.",
  ctaTitle: "Prendre l'ensemble",
  ctaSub: `MediaChef ${FACTS.version} — gratuit, open source, macOS · Windows · Linux.`,
  also: [
    { page: "mp3", label: "Convertir MP4 en MP3 — gratuit et hors ligne" },
    { page: "transcribe", label: "Transcrire l'audio en texte — hors ligne, avec Whisper" },
  ],
};

export default { ui, landings, catalog };
