// Тексты локали «it». Структура зеркальна остальным локалям.
import { FACTS } from "../facts";

export const ui = {
  title: "MediaChef — convertitore video e audio offline con trascrizione",
  description:
    "App gratuita e open source per macOS, Windows e Linux: converti video e audio sul tuo computer e trasforma il parlato in testo con Whisper. Senza caricamenti, senza limiti di dimensione, senza abbonamento.",
  nav: { recipes: "Ricette", transcribe: "Trascrizione", privacy: "Offline", faq: "Domande" },
  skipToContent: "Vai al contenuto",
  heroTitle1: "Qualsiasi file, in qualsiasi formato.",
  heroTitle2: "Il parlato, in testo.",
  heroAccent: "Tutto sul tuo computer.",
  heroSub:
    "MediaChef è un'app gratuita che trasforma FFmpeg e Whisper in schede ricetta: converti video e audio, estrai il suono da un clip, trasforma una registrazione in testo — offline, sulla tua macchina, senza caricare nulla da nessuna parte.",
  trust: [
    `Versione ${FACTS.version}`,
    `${FACTS.recipeCount} ricette incluse`,
    `${FACTS.modelCount} modelli Whisper`,
    "macOS · Windows · Linux",
    "Open source · GPL-3.0",
  ],
  ctaMac: "Scarica per macOS",
  ctaWin: "Scarica per Windows",
  ctaLinux: "Scarica per Linux",
  ctaNote: "Gratuito e open source —",
  ctaNoteLink: "guarda il codice su GitHub",
  howTitle: "Come funziona",
  steps: [
    { n: "1", h: "Trascina un file", p: "Trascina un video o una registrazione. MediaChef analizza il file e mostra solo le ricette adatte a ciò che ha trovato dentro." },
    { n: "2", h: "Scegli una ricetta", p: "Ogni azione è una scheda semplice: «Estrai audio in MP3», «Crea sottotitoli SRT per un video», «Comprimi video». I valori predefiniti sono già sensati e l'anteprima mostra il comando FFmpeg esatto." },
    { n: "3", h: "Ritira il risultato", p: "Il file compare accanto all'originale — o nella cartella che scegli tu. La coda mostra avanzamento, tempo rimanente e dove è finito il risultato." },
  ],
  shotAlt:
    "Schermata principale di MediaChef: menu laterale con Conversione, Modelli e Impostazioni, un'area per trascinare i file e la coda delle attività a destra.",
  shotCaption:
    "La finestra vera, nello stesso tema in cui stai leggendo. L'area dei file al centro, la coda a destra, i motori già dentro.",
  outTitle: "Cosa fa appena installata",
  outLead:
    "L'app include diciassette ricette. Ognuna è un vero lavoro di FFmpeg o Whisper con i parametri già impostati, e ognuna scrive il risultato accanto al tuo file come {nome}.{cosa}.{estensione}.",
  outHead: ["Direzione", "Ricetta nell'app", "Cosa ottieni"],
  outRows: [
    ["Video → audio", "Estrai audio in MP3", "<code>clip.audio.mp3</code> a 128, 192 o 320 kbps"],
    ["Video → sottotitoli", "Crea sottotitoli SRT", "<code>clip.subs.srt</code> con i tempi"],
    ["Audio → testo", "Trascrivi audio in testo", "<code>talk.transcript.txt</code>, testo semplice"],
    ["Qualsiasi lingua → inglese", "Traduci il parlato in testo inglese", "<code>talk.english.txt</code> in un solo passaggio"],
    ["MP4 → MKV", "Converti MP4 in MKV", "Reimpacchettato, non ricodificato — secondi, senza perdita"],
    ["Video → più leggero", "Comprimi video (preset di qualità)", "H.264 con CRF 23, 28 o 33"],
    ["Video → GIF", "Video in GIF", "10–24 fps, larghezza 320–640"],
    ["Tutto il resto", "Comando FFmpeg personalizzato", "I tuoi argomenti, con l'anteprima del comando"],
  ],
  modelsTitle: "Modelli Whisper",
  modelsLead:
    "La trascrizione gira su whisper.cpp con i modelli Whisper di OpenAI. Scarichi un modello una volta dalla schermata Modelli; dopo di che tutto funziona con la rete spenta. Modello più grande, testo migliore, elaborazione più lunga.",
  modelsHead: ["Modello", "Download", "A cosa serve"],
  modelSizes: {
    tiny: "78 MB",
    base: "148 MB",
    small: "488 MB",
    "large-v3-turbo": "1,62 GB",
  },
  modelNotes: {
    tiny: "Il più veloce, qualità approssimativa. Una bozza di parlato chiaro in una frazione del tempo.",
    base: "Veloce, qualità discreta. Basta per ritrovare in una registrazione il passaggio che ti serve.",
    small: "L'equilibrio consigliato — il valore predefinito in tutte le ricette di trascrizione.",
    "large-v3-turbo": "La qualità migliore, ottimizzato per Apple Silicon. Per testo destinato alla pubblicazione.",
  },
  defaultTag: "predefinito",
  recipesTitle: "Ricette al posto dei comandi",
  recipesLead:
    "FFmpeg sa fare quasi tutto — nella lingua del terminale. MediaChef traduce: scegli cosa fare, i parametri sono già pronti. L'anteprima mostra il comando reale, così lo impari strada facendo.",
  recipes: [
    { tile: "tile-ochre", h: "Estrai audio in MP3", p: "Tira fuori la traccia sonora da qualsiasi video." },
    { tile: "tile-green", h: "Crea sottotitoli SRT", p: "Whisper ascolta e scrive un file SRT." },
    { tile: "tile-green", h: "Comprimi video", p: "Fai stare un clip nella dimensione accettata dalla messaggistica." },
    { tile: "tile-purple", h: "Video in GIF", p: "Una GIF nitida in loop, da 10 a 24 fps." },
    { tile: "tile-green", h: "Trascrivi audio in testo", p: "Una riunione o un messaggio vocale in testo semplice." },
    { tile: "tile-blue", h: "Traduci il parlato in inglese", p: "Whisper trascrive e traduce in un solo passaggio." },
    { tile: "tile-blue", h: "Converti MP4 in MKV", p: "Reimpacchetta senza ricodificare — istantaneo." },
    { tile: "tile-red", h: "Togli l'audio dal video", p: "Elimina tutte le tracce audio e tieni l'immagine." },
  ],
  trTitle: "Trascrivi l'audio in testo senza uscire dal tuo computer",
  trBullets: [
    { h: "Whisper gira in locale.", p: "Il modello vocale di OpenAI viene eseguito sul tuo processore tramite whisper.cpp — le registrazioni non lasciano mai la macchina." },
    { h: "Modelli scaricati nell'app.", p: "Da tiny, 78 MB, a large-v3-turbo, 1,62 GB — scegli in base al lavoro dalla schermata Modelli." },
    { h: "Testo o sottotitoli.", p: "TXT semplice, SRT e VTT con i tempi, oppure JSON con il tempo di ogni segmento per i tuoi strumenti." },
    { h: "Risultati onesti.", p: "Se in un file non c'è parlato, MediaChef lo dice: «Nessun parlato rilevato» — non consegna mai un file vuoto con la spunta verde." },
  ],
  recipesLink: "Guida completa: convertire MP4 in MP3 →",
  trLink: "Guida completa: trascrivere audio in testo →",
  privTitle: "I tuoi file non vanno da nessuna parte",
  privLead:
    "Un convertitore online ti chiede di caricare il file sul server di qualcun altro, aspettare in coda e fidarti della sua politica di conservazione. MediaChef lavora sulla tua CPU: un gigabyte di registrazione dello schermo e l'audio privato di una riunione si convertono allo stesso modo — con il Wi-Fi spento.",
  privChips: ["Nessun caricamento", "Nessun limite di dimensione", "Nessun abbonamento"],
  ossTitle: "Open source, motori inclusi",
  ossLead:
    "GPL-3.0, con tutta la storia dello sviluppo pubblica su GitHub. Dalla 0.4.0 ogni download porta con sé i propri motori — niente da installare nel PATH, niente da configurare.",
  engineRows: [
    { k: `FFmpeg ${FACTS.ffmpeg}`, v: "conversione · GPL v3" },
    { k: `whisper.cpp ${FACTS.whisper}`, v: "riconoscimento vocale · MIT" },
    { k: "macOS · Windows · Linux", v: "dmg ~66 MB · installer ~82 MB · AppImage ~181 MB · deb ~118 MB" },
  ],
  ossNotice: "Versioni e licenze esatte di tutto ciò che è incluso — NOTICE.md",
  faqTitle: "Domande frequenti",
  faq: [
    { q: "È davvero gratuito?", a: "Sì. MediaChef è open source sotto GPL-3.0 — nessun account, nessuna prova, nessuna filigrana. Il convertitore e la trascrizione sono l'intera app, e il codice è pubblico su GitHub." },
    { q: "Quali formati sono supportati?", a: "Tutto ciò che FFmpeg legge: MP4, MKV, MOV, WebM, AVI, TS, MP3, WAV, FLAC, M4A, OGG e decine di altri. MediaChef analizza il file con ffprobe invece di fidarsi dell'estensione, quindi le ricette che vedi sono quelle che si adattano davvero." },
    { q: "Dove vengono caricati i miei file?", a: "Da nessuna parte. Conversione e trascrizione vengono eseguite interamente sul tuo computer. L'unica cosa che MediaChef scarica è un modello Whisper — una volta sola, dalla schermata Modelli." },
    { q: "Quanto è accurata la trascrizione?", a: "Usa i modelli Whisper di OpenAI tramite whisper.cpp v1.7.6. L'accuratezza dipende dal modello scelto: tiny è immediato e approssimativo, small è l'equilibrio predefinito, large-v3-turbo sfiora il livello umano su parlato chiaro. La lingua viene rilevata automaticamente." },
    { q: "Funziona offline?", a: "Sì. FFmpeg e Whisper viaggiano dentro il download, quindi la conversione funziona offline dal primo avvio, e la trascrizione dal momento in cui hai scaricato un modello una volta." },
    { q: "Perché non usare un convertitore online?", a: "Per un file piccolo e pubblico, un convertitore online va benissimo. Registrazioni private, video da più gigabyte, lotti e qualsiasi cosa coperta da riservatezza si trattano meglio in locale: nessuna attesa di caricamento, nessun tetto di dimensione e niente che resti sul disco di qualcun altro." },
  ],
  finalTitle: "Metti uno chef al comando dei tuoi file",
  finalSub: `Gratuito, open source, ${FACTS.platformCount} piattaforme. Versione ${FACTS.version}.`,
  betaNote:
    "MediaChef è giovane: le build non sono ancora firmate da Apple né da Microsoft, quindi il primo avvio chiede conferma — dentro ogni download c'è una guida in testo semplice.",
  footRights: "© 2026 mediachef.app · GPL-3.0",
  footTagline: "Una cucina multimediale open source.",
  tocLabel: "In questa pagina",
  breadcrumbHome: "Home",
  alsoLabel: "Da leggere dopo",
  footNavLabel: "Link del progetto",

  menu: {
    navLabel: "Sito",
    menu: "Menu",
    features: "Funzioni",
    guides: "Guide",
    download: "Scarica",
    faq: "Domande",
    gConvert: "Conversione",
    gTranscribe: "Trascrizione",
    gTrust: "Privacy e codice",
    gMac: "macOS",
    gWin: "Windows",
    gLinux: "Linux",
    allFiles: "Tutti i file e le note di rilascio",
    footProduct: "Prodotto",
    footGuides: "Guide",
    footDownload: "Scarica",
    footProject: "Progetto",
    footBlurb: `Una cucina multimediale gratuita per macOS, Windows e Linux. FFmpeg ${FACTS.ffmpeg} e whisper.cpp ${FACTS.whisper} viaggiano dentro il download — non c'è nulla da installare a parte.`,
    license: "Licenza GPL-3.0",
    notice: "Cosa c'è dentro — NOTICE.md",
    sourceCode: "Codice sorgente su GitHub",
    releases: "Tutte le versioni",
    langLabel: "Lingua",
    // Подпись на схеме окна приложения в hero.
    dropHere: "Trascina qui i file",
    dlWin: "Windows · installer",
    nApple: "Apple Silicon",
    nZip: "Apple Silicon, senza installer",
    nWin: "64 bit",
    nAppimage: "x86_64, si avvia così com'è",
    nDeb: "x86_64, Debian e Ubuntu",
    sHow: "Come funziona",
    sRecipes: "Ricette",
    sOut: "Cosa fa appena installata",
    sTranscribe: "Trascrizione",
    sModels: "Modelli Whisper",
    sPrivacy: "Offline e privato",
    sOss: "Open source",
    sFaq: "Domande",
    pMp3: "MP4 in MP3",
    pTranscribe: "Audio in testo",
  },
};

export const landings = {
  mp3: {
    title: "Convertire MP4 in MP3 gratis e offline — MediaChef",
    description:
      "Estrai l'audio da un MP4 e salvalo come MP3 sul tuo computer: senza caricamenti, senza tetto di dimensione, senza filigrana. App gratuita e open source per macOS, Windows e Linux.",
    h1: "Convertire MP4 in MP3 — gratis, offline, sul tuo computer",
    crumb: "MP4 in MP3",
    lead:
      "MediaChef include una ricetta chiamata «Estrai audio in MP3». Trascina un video nell'area, scegli un bitrate, premi avvia: la traccia sonora viene scritta accanto all'originale come MP3. Il file non lascia mai la tua macchina, non c'è limite di dimensione e tutto funziona con la rete spenta.",
    sections: { how: "how", table: "bitrate", why: "offline", faq: "faq" },
    toc: ["Come convertire MP4 in MP3", "Quale bitrate scegliere", "Perché convertire sul tuo computer", "Domande"],
    stepsTitle: "Come convertire MP4 in MP3",
    steps: [
      { h: "Scarica MediaChef", p: "Un file per macOS, Windows o Linux. FFmpeg è già dentro — niente da installare a parte, niente da aggiungere al PATH." },
      { h: "Trascina l'MP4 nell'area", p: "MediaChef legge il file con ffprobe e tiene solo le ricette adatte. Un video con traccia audio riceve subito la scheda MP3." },
      { h: "Scegli «Estrai audio in MP3»", p: "Imposta il bitrate: 128k per il parlato, 192k come predefinito, 320k per archiviare. L'anteprima del comando si aggiorna a ogni cambio." },
      { h: "Premi avvia e ritira il file", p: "L'MP3 compare accanto al video come clip.audio.mp3. La coda mostra avanzamento, tempo rimanente e il percorso finale." },
    ],
    shotAlt:
      "MediaChef pronto a convertire MP4 in MP3: l'area attende un file video, con la coda delle attività a destra.",
    shotCaption: "L'area dove finisce l'MP4. Le ricette compaiono appena MediaChef ha letto il file.",
    tableTitle: "Quale bitrate scegliere",
    tableLead:
      "La ricetta offre tre bitrate. Le dimensioni qui sotto valgono per un'ora di audio — è aritmetica del bitrate, quindi una registrazione di due ore pesa semplicemente il doppio.",
    tableHead: ["Bitrate", "Un'ora di audio", "Scegli quando"],
    tableRows: [
      ["128 kbps", "≈ 58 MB", "Parlato: interviste, podcast, lezioni, note vocali. Il file più piccolo, senza perdita udibile su una voce."],
      ["192 kbps", "≈ 86 MB", "Il valore predefinito. Musica che ascolti davvero, e tutto ciò di cui non sei sicuro."],
      ["320 kbps", "≈ 144 MB", "Archiviazione, o audio che monterai ancora e ricodificherai in seguito."],
    ],
    tableNote:
      "Non solo MP4: la stessa ricetta compare per MKV, MOV, WebM, AVI, TS e qualsiasi altra cosa FFmpeg sappia leggere, purché il file abbia una traccia audio.",
    whyTitle: "Perché convertire sul tuo computer",
    whyBullets: [
      { h: "Non viene caricato nulla.", p: "Una chiamata registrata o un montaggio non ancora uscito resta sul tuo disco. Non esiste una copia sul server della cui politica di conservazione fidarsi." },
      { h: "Nessun tetto di dimensione.", p: "I convertitori online si fermano tra 100 MB e 2 GB e ti mettono in coda. Una registrazione dello schermo da quattro gigabyte si converte come una da quattro megabyte." },
      { h: "Più veloce sui file reali.", p: "Estrarre una traccia audio già presente è rapido. La parte lenta è caricare prima il video — e in locale quella parte non esiste." },
      { h: "Gratis, senza account.", p: "Open source GPL-3.0: nessuna registrazione, nessuna prova, nessuna filigrana, nessun limite per file." },
      { h: "A lotti, non uno alla volta.", p: "Trascina tutti i clip in una volta; la coda li lavora e ti dice dove è finito ogni MP3." },
    ],
    faqTitle: "Domande frequenti",
    faq: [
      { q: "Convertire MP4 in MP3 fa perdere qualità?", a: "L'MP3 è un formato con perdita, quindi la traccia viene ricodificata una volta. Ai 192 kbps predefiniti è impercettibile sul parlato e molto vicino a esserlo sulla musica. Se il file è un master su cui lavorerai ancora, scegli 320 kbps." },
      { q: "Qual è il file più grande che posso convertire?", a: "MediaChef non impone limiti — il limite è lo spazio libero sul disco, e l'app lo controlla prima di partire. Nemmeno la durata conta: una registrazione di tre ore è un solo lavoro in coda." },
      { q: "Funziona senza internet?", a: "Sì, del tutto. FFmpeg viaggia dentro il download, quindi la conversione non tocca mai la rete. Solo la trascrizione richiede di scaricare un modello una volta." },
      { q: "Posso convertire più video insieme?", a: "Sì. Trascinali tutti nell'area, aggiungi la ricetta e la coda li esegue uno dopo l'altro, con avanzamento e tempo rimanente per ciascuno." },
      { q: "C'è una filigrana o una versione a pagamento?", a: "No. MediaChef è open source GPL-3.0 senza alcuna versione a pagamento, e non tocca il tuo audio oltre la conversione che hai chiesto." },
      { q: "Se trasformo un MP4 in MP3, il video originale resta?", a: "Sì. MediaChef legge il video e scrive un MP3 nuovo accanto: l’MP4 non viene sovrascritto, rinominato né cancellato, quindi puoi estrarre l’audio dallo stesso file tutte le volte che vuoi. Non viene caricato nulla, tutto gira senza connessione." },
    ],
    ctaTitle: "Tira fuori l'MP3 da quel video",
    ctaSub: `MediaChef ${FACTS.version} — gratis, open source, macOS · Windows · Linux.`,
    also: [
      { page: "transcribe", label: "Trascrivere audio in testo — offline, con Whisper" },
      { page: "home", label: `Tutte le ${FACTS.recipeCount} ricette e come funziona MediaChef` },
    ],
  },
  transcribe: {
    title: "Trascrivere audio in testo offline con Whisper — MediaChef",
    description:
      "Trasforma le registrazioni in testo sul tuo computer con Whisper: TXT, SRT, VTT o JSON. Senza caricamenti, senza tariffa al minuto, senza limiti di durata. App gratuita per macOS, Windows e Linux.",
    h1: "Trascrivere audio in testo — offline, sul tuo computer",
    crumb: "Audio in testo",
    lead:
      "MediaChef esegue Whisper di OpenAI in locale tramite whisper.cpp. Scarica un modello una volta, poi trascina una registrazione o un video e scegli cosa vuoi in uscita: testo semplice, sottotitoli SRT o VTT con i tempi, oppure JSON con il tempo di ogni segmento. L'audio non viene mai caricato e non c'è un prezzo al minuto.",
    sections: { how: "how", table: "models", why: "offline", faq: "faq" },
    toc: ["Come trascrivere una registrazione", "Quale modello Whisper scegliere", "Perché trascrivere sul tuo computer", "Domande"],
    outLabel: "Cosa ottieni",
    outSample: "00:00:04  Ciao a tutti, cominciamo…\n00:00:11  Primo punto: i piani del trimestre.\n00:00:19  Ci sono tre scenari, vi mostro la tabella.",
    outNote: "TXT senza tempi, SRT e VTT con i tempi, JSON con inizio e fine di ogni segmento.",
    stepsTitle: "Come trascrivere una registrazione",
    steps: [
      { h: "Scarica MediaChef", p: "Un file per macOS, Windows o Linux. whisper.cpp v1.7.6 è già dentro il download; solo il modello si scarica a parte." },
      { h: "Scegli un modello Whisper", p: "Apri Modelli e scaricane uno — small (488 MB) è l'equilibrio predefinito. Si scarica una volta; dopo la trascrizione funziona con la rete spenta." },
      { h: "Trascina la registrazione o il video", p: "Vanno bene sia audio sia video: MediaChef estrae il suono dal video da solo, quindi la registrazione di una riunione e un MP4 seguono la stessa strada." },
      { h: "Scegli l'uscita che ti serve", p: "«Trascrivi audio in testo» per il TXT, «Trascrivi audio in sottotitoli SRT» o «Trascrivi audio in WebVTT» per sottotitoli con i tempi, «Trascrivi audio in JSON con i tempi» per gli strumenti." },
      { h: "Premi avvia e leggi il risultato", p: "Il testo finisce accanto al file come talk.transcript.txt. La coda mostra l'avanzamento; se nel file non c'è parlato, MediaChef lo dice invece di scriverne uno vuoto." },
    ],
    shotAlt:
      "MediaChef prima della trascrizione: l'area per trascinare una registrazione, con Modelli nel menu laterale da cui si scaricano i modelli Whisper.",
    shotCaption: "I modelli stanno nel menu laterale — scarichi una volta e poi trascrivi offline.",
    tableTitle: "Quale modello Whisper scegliere",
    tableLead:
      "Nel catalogo ci sono quattro modelli, scaricati dentro l'app. Più grande significa testo migliore ed elaborazione più lunga sulla stessa macchina, quindi scegli in base al lavoro e non una volta per sempre.",
    tableHead: ["Modello", "Download", "Quando sceglierlo"],
    tableRows: [
      ["tiny", "78 MB", "Un primo passaggio su parlato chiaro, o quando ti serve solo trovare dove inizia un argomento."],
      ["base", "148 MB", "Appunti per te: testo leggibile che comunque riguarderai e correggerai."],
      ["small", "488 MB", "Il predefinito in tutte le ricette di trascrizione, e quello con cui restano quasi tutti. Interviste, riunioni, lezioni."],
      ["large-v3-turbo", "1,62 GB", "Testo destinato ad altri: sottotitoli che pubblichi, citazioni che riporti. Ottimizzato per Apple Silicon."],
    ],
    tableNote:
      "La lingua viene rilevata automaticamente, e puoi anche fissarla. Due ricette aggiuntive traducono qualsiasi lingua in inglese — come testo o come sottotitoli con i tempi — nello stesso passaggio.",
    whyTitle: "Perché trascrivere sul tuo computer",
    whyBullets: [
      { h: "L'audio riservato resta riservato.", p: "Interviste, appunti clinici, telefonate legali, qualsiasi cosa sotto accordo di riservatezza: il file lo legge un processo sulla tua macchina e nient'altro." },
      { h: "Nessuna tariffa al minuto.", p: "La trascrizione nel cloud fattura al minuto. In locale la decima ora di audio costa quanto la prima: nulla." },
      { h: "Nessun limite di durata o dimensione.", p: "Una registrazione di quattro ore è un lavoro in coda, non un piano a pagamento né un espediente per spezzare il file." },
      { h: "Funziona senza alcuna rete.", p: "Una volta che il modello è sul disco, la trascrizione è offline: in aereo, in laboratorio, su una macchina isolata." },
      { h: "Sottotitoli e testo dallo stesso passaggio.", p: "SRT e VTT portano i tempi per un lettore, TXT è prosa pulita, JSON ha i tempi dei segmenti per i tuoi script." },
    ],
    faqTitle: "Domande frequenti",
    faq: [
      { q: "Quanto è accurata la trascrizione di Whisper?", a: "L'accuratezza dipende dal modello: tiny è una bozza, small è l'equilibrio predefinito, large-v3-turbo sfiora il livello umano su parlato chiaro. L'audio pulito con un solo parlante è quello che riesce meglio; accenti marcati, persone che parlano sovrapposte e musica sotto la voce costano accuratezza — come per qualsiasi sistema di riconoscimento vocale." },
      { q: "Quali lingue gestisce?", a: "Whisper copre un centinaio di lingue e rileva la lingua da solo; puoi anche fissarla se sbaglia. Due ricette traducono il parlato da qualsiasi di esse in inglese in un solo passaggio, come testo o come sottotitoli SRT." },
      { q: "In quali formati esce la trascrizione?", a: "TXT per il testo semplice, SRT e VTT con i tempi per lettori e programmi di montaggio, e JSON con inizio e fine di ogni segmento per script e strumenti." },
      { q: "Serve internet?", a: "Una volta, per scaricare un modello Whisper dalla schermata Modelli — da 78 MB a 1,62 GB a seconda di quale scegli. Dopo, la trascrizione gira interamente offline." },
      { q: "E se la registrazione non contiene parlato?", a: "MediaChef segnala «Nessun parlato rilevato» invece di scrivere un file vuoto e spuntare il lavoro in verde. Silenzio, musica senza voce e un file scelto per errore finiscono con la stessa onestà." },
      { q: "Posso trasformare un video in testo o solo l’audio?", a: "Il video funziona allo stesso modo. MediaChef estrae l’audio dal file stesso, quindi un MP4, MKV o MOV va dritto alla trascrizione: c’è perfino una ricetta a parte, «Ricava il testo da un video». Non devi cambiarlo prima in audio." },
    ],
    ctaTitle: "Trasforma quella registrazione in testo",
    ctaSub: `MediaChef ${FACTS.version} — Whisper in locale, gratuito e open source.`,
    also: [
      { page: "mp3", label: "Convertire MP4 in MP3 — gratis e offline" },
      { page: "home", label: `Tutte le ${FACTS.recipeCount} ricette e come funziona MediaChef` },
    ],
  },
};

export default { ui, landings };
