// Тексты локали «pl». Структура зеркальна остальным локалям.
import { FACTS } from "../facts";

export const ui = {
  title: "MediaChef — offline'owy konwerter wideo i audio z transkrypcją",
  description:
    "Darmowa aplikacja open source na macOS, Windows i Linux: konwertuj wideo i audio na własnym komputerze i zamieniaj mowę na tekst przy pomocy Whisper. Bez wysyłania plików, bez limitu rozmiaru, bez abonamentu.",
  nav: { recipes: "Przepisy", transcribe: "Transkrypcja", privacy: "Offline", faq: "Pytania" },
  skipToContent: "Przejdź do treści",
  heroTitle1: "Każdy plik na każdy format.",
  heroTitle2: "Mowa na tekst.",
  heroAccent: "Wszystko na twoim komputerze.",
  heroSub:
    "MediaChef to darmowa aplikacja, która zamienia FFmpeg i Whisper w karty przepisów: konwertuj wideo i audio, wyciągaj dźwięk z klipu, zamieniaj nagranie w tekst — offline, na własnym komputerze, bez wysyłania czegokolwiek gdziekolwiek.",
  trust: [
    `Wersja ${FACTS.version}`,
    `${FACTS.recipeCount} gotowych przepisów`,
    `${FACTS.modelCount} modele Whisper`,
    "macOS · Windows · Linux",
    "Otwarty kod · GPL-3.0",
  ],
  ctaMac: "Pobierz na macOS",
  ctaWin: "Pobierz na Windows",
  ctaLinux: "Pobierz na Linux",
  ctaNote: "Za darmo i z otwartym kodem —",
  ctaNoteLink: "zobacz kod na GitHubie",
  howTitle: "Jak to działa",
  steps: [
    { n: "1", h: "Upuść plik", p: "Przeciągnij wideo albo nagranie. MediaChef zagląda do środka pliku i pokazuje tylko te przepisy, które do niego pasują." },
    { n: "2", h: "Wybierz przepis", p: "Każde działanie to zwykła karta: „Wyciągnij audio do MP3”, „Zrób napisy SRT do wideo”, „Skompresuj wideo”. Ustawienia domyślne są już sensowne, a podgląd pokazuje dokładne polecenie FFmpeg." },
    { n: "3", h: "Odbierz wynik", p: "Plik pojawia się obok oryginału — albo w wybranym przez ciebie folderze. Kolejka pokazuje postęp, pozostały czas i miejsce, w którym wylądował wynik." },
  ],
  shotAlt:
    "Główny ekran MediaChef: menu boczne z Konwersją, Modelami i Ustawieniami, pole na pliki oraz kolejka zadań po prawej.",
  shotCaption:
    "Prawdziwe okno, w tym samym motywie, w którym właśnie czytasz. Pole na pliki pośrodku, kolejka po prawej, silniki już w środku.",
  outTitle: "Co potrafi zaraz po instalacji",
  outLead:
    "W aplikacji jest siedemnaście przepisów. Każdy to prawdziwe zadanie FFmpeg albo Whisper z gotowymi parametrami, i każdy zapisuje wynik obok twojego pliku jako {nazwa}.{co}.{rozszerzenie}.",
  outHead: ["Kierunek", "Przepis w aplikacji", "Co dostajesz"],
  outRows: [
    ["Wideo → audio", "Wyciągnij audio do MP3", "<code>clip.audio.mp3</code> w 128, 192 lub 320 kbps"],
    ["Wideo → napisy", "Zrób napisy SRT do wideo", "<code>clip.subs.srt</code> z czasami"],
    ["Audio → tekst", "Przepisz audio na tekst", "<code>talk.transcript.txt</code>, zwykły tekst"],
    ["Dowolny język → angielski", "Przetłumacz mowę na tekst angielski", "<code>talk.english.txt</code> w jednym przebiegu"],
    ["MP4 → MKV", "Konwertuj MP4 na MKV", "Przepakowanie bez ponownego kodowania — sekundy, bez straty jakości"],
    ["Wideo → mniejsze", "Skompresuj wideo (ustawienie jakości)", "H.264 z CRF 23, 28 lub 33"],
    ["Wideo → GIF", "Wideo na GIF", "10–24 kl./s, szerokość 320–640"],
    ["Cała reszta", "Własne polecenie FFmpeg", "Twoje własne argumenty, z podglądem polecenia"],
  ],
  modelsTitle: "Modele Whisper",
  modelsLead:
    "Transkrypcja działa na whisper.cpp z modelami Whisper od OpenAI. Model pobierasz raz na ekranie Modele; potem wszystko działa przy wyłączonej sieci. Większy model — lepszy tekst i dłuższe liczenie.",
  modelsHead: ["Model", "Pobranie", "Do czego"],
  modelSizes: {
    tiny: "78 MB",
    base: "148 MB",
    small: "488 MB",
    "large-v3-turbo": "1,62 GB",
  },
  modelNotes: {
    tiny: "Najszybszy, jakość zgrubna. Szkic wyraźnej mowy w ułamku czasu.",
    base: "Szybki, przyzwoita jakość. Wystarczy, żeby znaleźć w nagraniu potrzebny fragment.",
    small: "Zalecana równowaga — domyślny we wszystkich przepisach transkrypcji.",
    "large-v3-turbo": "Najlepsza jakość, zoptymalizowany pod Apple Silicon. Do tekstu, który pójdzie do publikacji.",
  },
  defaultTag: "domyślnie",
  recipesTitle: "Przepisy zamiast poleceń",
  recipesLead:
    "FFmpeg potrafi prawie wszystko — w języku terminala. MediaChef tłumaczy: ty wybierasz, co zrobić, parametry są już ustawione. Podgląd pokazuje prawdziwe polecenie, więc przy okazji się go uczysz.",
  recipes: [
    { tile: "tile-ochre", h: "Wyciągnij audio do MP3", p: "Wyjmij ścieżkę dźwiękową z dowolnego wideo." },
    { tile: "tile-green", h: "Zrób napisy SRT", p: "Whisper słucha i zapisuje plik SRT." },
    { tile: "tile-green", h: "Skompresuj wideo", p: "Zmieść klip w rozmiarze, który przyjmie komunikator." },
    { tile: "tile-purple", h: "Wideo na GIF", p: "Ostry GIF w pętli, od 10 do 24 kl./s." },
    { tile: "tile-green", h: "Przepisz audio na tekst", p: "Spotkanie albo wiadomość głosowa w zwykłym tekście." },
    { tile: "tile-blue", h: "Przetłumacz mowę na angielski", p: "Whisper przepisuje i tłumaczy w jednym przebiegu." },
    { tile: "tile-blue", h: "Konwertuj MP4 na MKV", p: "Przepakowanie bez ponownego kodowania — natychmiast." },
    { tile: "tile-red", h: "Usuń dźwięk z wideo", p: "Skasuj wszystkie ścieżki audio, zostaw obraz." },
  ],
  trTitle: "Przepisz audio na tekst bez wychodzenia z komputera",
  trBullets: [
    { h: "Whisper działa lokalnie.", p: "Model mowy od OpenAI wykonuje się na twoim procesorze przez whisper.cpp — nagrania nigdy nie opuszczają komputera." },
    { h: "Modele pobierane w aplikacji.", p: "Od tiny na 78 MB po large-v3-turbo na 1,62 GB — wybierz pod zadanie na ekranie Modele." },
    { h: "Tekst albo napisy.", p: "Zwykły TXT, SRT i VTT ze znacznikami czasu albo JSON z czasem każdego fragmentu dla twoich narzędzi." },
    { h: "Uczciwy wynik.", p: "Jeśli w pliku nie ma mowy, MediaChef tak powie: „Nie wykryto mowy” — zamiast pustego pliku z zielonym ptaszkiem." },
  ],
  recipesLink: "Pełny poradnik: konwersja MP4 na MP3 →",
  trLink: "Pełny poradnik: przepisanie audio na tekst →",
  privTitle: "Twoje pliki nigdzie nie jadą",
  privLead:
    "Konwerter online prosi, żebyś wysłał plik na cudzy serwer, poczekał w kolejce i zaufał jego polityce przechowywania. MediaChef pracuje na twoim procesorze: gigabajtowe nagranie ekranu i prywatne nagranie spotkania konwertują się tak samo — przy wyłączonym Wi-Fi.",
  privChips: ["Bez wysyłania", "Bez limitu rozmiaru", "Bez abonamentu"],
  ossTitle: "Otwarty kod, silniki w komplecie",
  ossLead:
    "GPL-3.0, cała historia rozwoju jest publiczna na GitHubie. Od wersji 0.4.0 każde pobranie niesie własne silniki — nic do instalowania w PATH, nic do konfigurowania.",
  engineRows: [
    { k: `FFmpeg ${FACTS.ffmpeg}`, v: "konwersja · GPL v3" },
    { k: `whisper.cpp ${FACTS.whisper}`, v: "rozpoznawanie mowy · MIT" },
    { k: "macOS · Windows · Linux", v: "dmg ~66 MB · instalator ~82 MB · AppImage ~181 MB · deb ~118 MB" },
  ],
  ossNotice: "Dokładne wersje i licencje wszystkiego, co w środku — NOTICE.md",
  faqTitle: "Częste pytania",
  faq: [
    { q: "Czy to naprawdę za darmo?", a: "Tak. MediaChef ma otwarty kod na licencji GPL-3.0 — bez konta, bez okresu próbnego, bez znaku wodnego. Konwerter i transkrypcja to cała aplikacja, a kod jest publiczny na GitHubie." },
    { q: "Jakie formaty są obsługiwane?", a: "Wszystko, co czyta FFmpeg: MP4, MKV, MOV, WebM, AVI, TS, MP3, WAV, FLAC, M4A, OGG i dziesiątki innych. MediaChef zagląda do pliku przez ffprobe, zamiast wierzyć rozszerzeniu, więc widoczne przepisy to te, które naprawdę pasują." },
    { q: "Gdzie trafiają moje pliki?", a: "Nigdzie. Konwersja i transkrypcja wykonują się w całości na twoim komputerze. Jedyne, co MediaChef kiedykolwiek pobiera, to model Whisper — raz, na ekranie Modele." },
    { q: "Jak dokładna jest transkrypcja?", a: "Korzysta z modeli Whisper od OpenAI przez whisper.cpp v1.7.6. Dokładność zależy od wybranego modelu: tiny jest natychmiastowy i zgrubny, small to zrównoważona wartość domyślna, large-v3-turbo przy wyraźnej mowie zbliża się do poziomu człowieka. Język wykrywany jest automatycznie." },
    { q: "Czy działa offline?", a: "Tak. FFmpeg i Whisper jadą wewnątrz pobrania, więc konwersja działa offline od pierwszego uruchomienia, a transkrypcja — gdy raz pobierzesz model." },
    { q: "Po co, skoro jest konwerter online?", a: "Do jednego małego, publicznego pliku konwerter online w zupełności wystarczy. Prywatne nagrania, wielogigabajtowe filmy, partie plików i wszystko objęte poufnością lepiej robić lokalnie: bez czekania na wysyłkę, bez limitu rozmiaru i bez niczego leżącego na cudzym dysku." },
  ],
  finalTitle: "Postaw szefa kuchni przy swoich plikach",
  finalSub: `Za darmo, otwarty kod, ${FACTS.platformCount} platformy. Wersja ${FACTS.version}.`,
  betaNote:
    "MediaChef jest młody: kompilacje nie są jeszcze podpisane przez Apple ani Microsoft, więc pierwsze uruchomienie prosi o potwierdzenie — w każdym pobraniu jest instrukcja w zwykłym tekście.",
  footRights: "© 2026 mediachef.app · GPL-3.0",
  footTagline: "Otwartoźródłowa kuchnia mediów.",
  tocLabel: "Na tej stronie",
  breadcrumbHome: "Strona główna",
  alsoLabel: "Czytaj dalej",
  footNavLabel: "Linki projektu",

  menu: {
    navLabel: "Serwis",
    menu: "Menu",
    features: "Możliwości",
    guides: "Poradniki",
    download: "Pobierz",
    faq: "Pytania",
    gConvert: "Konwersja",
    gTranscribe: "Transkrypcja",
    gTrust: "Prywatność i kod",
    gMac: "macOS",
    gWin: "Windows",
    gLinux: "Linux",
    allFiles: "Wszystkie pliki i informacje o wydaniu",
    footProduct: "Produkt",
    footGuides: "Poradniki",
    footDownload: "Pobierz",
    footProject: "Projekt",
    footBlurb: `Darmowa kuchnia mediów na macOS, Windows i Linux. FFmpeg ${FACTS.ffmpeg} i whisper.cpp ${FACTS.whisper} jadą wewnątrz pobrania — nie ma czego instalować osobno.`,
    license: "Licencja GPL-3.0",
    notice: "Co jest w środku — NOTICE.md",
    sourceCode: "Kod źródłowy na GitHubie",
    releases: "Wszystkie wydania",
    langLabel: "Język",
    // Подпись на схеме окна приложения в hero.
    dropHere: "Upuść pliki tutaj",
    dlWin: "Windows · instalator",
    nApple: "Apple Silicon",
    nZip: "Apple Silicon, bez instalatora",
    nWin: "64-bitowy",
    nAppimage: "x86_64, uruchamia się od razu",
    nDeb: "x86_64, Debian i Ubuntu",
    sHow: "Jak to działa",
    sRecipes: "Przepisy",
    sOut: "Co potrafi od razu",
    sTranscribe: "Transkrypcja",
    sModels: "Modele Whisper",
    sPrivacy: "Offline i prywatnie",
    sOss: "Otwarty kod",
    sFaq: "Pytania",
    pMp3: "MP4 na MP3",
    pTranscribe: "Audio na tekst",
  },
};

export const landings = {
  mp3: {
    title: "Konwersja MP4 na MP3 za darmo i offline — MediaChef",
    description:
      "Wyciągnij dźwięk z MP4 i zapisz go jako MP3 na własnym komputerze: bez wysyłania, bez limitu rozmiaru, bez znaku wodnego. Darmowa aplikacja open source na macOS, Windows i Linux.",
    h1: "Konwersja MP4 na MP3 — za darmo, offline, na twoim komputerze",
    crumb: "MP4 na MP3",
    lead:
      "MediaChef ma przepis o nazwie „Wyciągnij audio do MP3”. Upuść wideo na pole, wybierz bitrate, naciśnij start: ścieżka dźwiękowa zapisze się obok oryginału jako MP3. Plik nigdy nie opuszcza twojej maszyny, nie ma limitu rozmiaru, a całość działa przy wyłączonej sieci.",
    sections: { how: "how", table: "bitrate", why: "offline", faq: "faq" },
    toc: ["Jak przekonwertować MP4 na MP3", "Jaki bitrate wybrać", "Dlaczego konwertować u siebie", "Pytania"],
    stepsTitle: "Jak przekonwertować MP4 na MP3",
    steps: [
      { h: "Pobierz MediaChef", p: "Jeden plik na macOS, Windows albo Linux. FFmpeg jest już w środku — nic nie trzeba instalować osobno ani dopisywać do PATH." },
      { h: "Upuść MP4 na pole", p: "MediaChef czyta plik przez ffprobe i zostawia tylko pasujące przepisy. Wideo ze ścieżką dźwiękową od razu dostaje kartę MP3." },
      { h: "Wybierz „Wyciągnij audio do MP3”", p: "Ustaw bitrate: 128k do mowy, 192k domyślnie, 320k do archiwum. Podgląd polecenia zmienia się przy przełączaniu." },
      { h: "Naciśnij start i odbierz plik", p: "MP3 pojawia się obok wideo jako clip.audio.mp3. Kolejka pokazuje postęp, pozostały czas i gotową ścieżkę." },
    ],
    shotAlt:
      "MediaChef gotowy do konwersji MP4 na MP3: pole czeka na plik wideo, po prawej kolejka zadań.",
    shotCaption: "Pole, na które trafia MP4. Przepisy pojawiają się, gdy MediaChef przeczyta plik.",
    tableTitle: "Jaki bitrate wybrać",
    tableLead:
      "Przepis oferuje trzy bitrate'y. Rozmiary poniżej dotyczą godziny dźwięku — to zwykła arytmetyka z bitrate'u, więc dwugodzinne nagranie waży po prostu dwa razy tyle.",
    tableHead: ["Bitrate", "Godzina dźwięku", "Wybierz, gdy"],
    tableRows: [
      ["128 kbps", "≈ 58 MB", "Mowa: wywiady, podcasty, wykłady, notatki głosowe. Najmniejszy plik, bez słyszalnej straty na głosie."],
      ["192 kbps", "≈ 86 MB", "Wartość domyślna. Muzyka, której naprawdę słuchasz, i wszystko, czego nie jesteś pewien."],
      ["320 kbps", "≈ 144 MB", "Archiwum albo dźwięk, który będziesz jeszcze montować i ponownie kodować."],
    ],
    tableNote:
      "Nie tylko MP4: ten sam przepis pojawia się dla MKV, MOV, WebM, AVI, TS i wszystkiego innego, co FFmpeg umie przeczytać — o ile plik ma ścieżkę dźwiękową.",
    whyTitle: "Dlaczego konwertować u siebie",
    whyBullets: [
      { h: "Nic nie jest wysyłane.", p: "Nagrana rozmowa albo niewydany montaż zostaje na twoim dysku. Nie ma kopii na serwerze, której polityce przechowywania trzeba by wierzyć." },
      { h: "Bez limitu rozmiaru.", p: "Konwertery online kończą się między 100 MB a 2 GB i wstawiają cię do kolejki. Czterogigabajtowe nagranie ekranu konwertuje się tak samo jak czteromegabajtowe." },
      { h: "Szybciej na prawdziwych plikach.", p: "Wyciągnięcie istniejącej ścieżki dźwiękowej jest szybkie. Wolne jest wcześniejsze wysłanie wideo — a lokalnie tego kroku po prostu nie ma." },
      { h: "Za darmo, bez konta.", p: "Otwarty kod GPL-3.0: bez rejestracji, bez okresu próbnego, bez znaku wodnego, bez limitu na plik." },
      { h: "Partiami, a nie po jednym.", p: "Upuść wszystkie klipy naraz; kolejka je przerobi i powie, gdzie wylądował każdy MP3." },
    ],
    faqTitle: "Częste pytania",
    faq: [
      { q: "Czy konwersja MP4 na MP3 traci jakość?", a: "MP3 to format stratny, więc ścieżka jest raz kodowana ponownie. Przy domyślnych 192 kbps na mowie tego nie słychać, a na muzyce jest bardzo blisko. Jeśli plik to master, nad którym będziesz jeszcze pracować, weź 320 kbps." },
      { q: "Jak duży plik mogę przekonwertować?", a: "MediaChef nie ustawia limitu — limitem jest wolne miejsce na dysku, a aplikacja sprawdza je przed startem. Długość też nie ma znaczenia: trzygodzinne nagranie to jedno zadanie w kolejce." },
      { q: "Czy działa bez internetu?", a: "Tak, całkowicie. FFmpeg jedzie wewnątrz pobrania, więc konwersja nigdy nie dotyka sieci. Tylko transkrypcja wymaga jednorazowego pobrania modelu." },
      { q: "Czy mogę przekonwertować kilka filmów naraz?", a: "Tak. Upuść wszystkie na pole, dodaj przepis, a kolejka wykona je jeden po drugim, z postępem i pozostałym czasem dla każdego." },
      { q: "Czy jest znak wodny albo wersja płatna?", a: "Nie. MediaChef to otwarty kod GPL-3.0 zupełnie bez wersji płatnej i nie rusza twojego dźwięku poza konwersją, o którą poprosiłeś." },
    ],
    ctaTitle: "Wyciągnij MP3 z tego wideo",
    ctaSub: `MediaChef ${FACTS.version} — za darmo, otwarty kod, macOS · Windows · Linux.`,
    also: [
      { page: "transcribe", label: "Przepisz audio na tekst — offline, przez Whisper" },
      { page: "home", label: `Wszystkie ${FACTS.recipeCount} przepisów i jak działa MediaChef` },
    ],
  },
  transcribe: {
    title: "Transkrypcja audio na tekst offline z Whisper — MediaChef",
    description:
      "Zamień nagrania w tekst na własnym komputerze przy pomocy Whisper: TXT, SRT, VTT albo JSON. Bez wysyłania, bez opłaty za minutę, bez limitu długości. Darmowa aplikacja na macOS, Windows i Linux.",
    h1: "Transkrypcja audio na tekst — offline, na własnym komputerze",
    crumb: "Audio na tekst",
    lead:
      "MediaChef uruchamia Whisper od OpenAI lokalnie, przez whisper.cpp. Pobierz model raz, potem upuść nagranie albo wideo i wybierz, co ma z tego wyjść: zwykły tekst, napisy SRT lub VTT z czasami, albo JSON z czasem każdego fragmentu. Dźwięk nigdy nie jest wysyłany i nie ma opłaty za minutę.",
    sections: { how: "how", table: "models", why: "offline", faq: "faq" },
    toc: ["Jak przepisać nagranie", "Który model Whisper wybrać", "Dlaczego przepisywać u siebie", "Pytania"],
    outLabel: "Co z tego wychodzi",
    outSample: "00:00:04  Cześć wszystkim, zaczynamy…\n00:00:11  Pierwszy punkt: plany na kwartał.\n00:00:19  Są trzy scenariusze, pokażę tabelę.",
    outNote: "TXT bez czasów, SRT i VTT z nimi, JSON z początkiem i końcem każdego fragmentu.",
    stepsTitle: "Jak przepisać nagranie",
    steps: [
      { h: "Pobierz MediaChef", p: "Jeden plik na macOS, Windows albo Linux. whisper.cpp v1.7.6 jest już w pobraniu; osobno pobiera się tylko model." },
      { h: "Wybierz model Whisper", p: "Otwórz Modele i pobierz jeden — small (488 MB) to zrównoważona wartość domyślna. Pobiera się raz; potem transkrypcja działa przy wyłączonej sieci." },
      { h: "Upuść nagranie albo wideo", p: "Działa i audio, i wideo: MediaChef sam wyciąga dźwięk z filmu, więc nagranie spotkania i MP4 idą tą samą drogą." },
      { h: "Wybierz potrzebne wyjście", p: "„Przepisz audio na tekst” dla TXT, „Przepisz audio na napisy SRT” albo „Przepisz audio na WebVTT” dla napisów z czasami, „Przepisz audio na JSON z czasami” dla narzędzi." },
      { h: "Naciśnij start i czytaj", p: "Tekst ląduje obok pliku jako talk.transcript.txt. Kolejka pokazuje postęp; jeśli w pliku nie ma mowy, MediaChef to powie zamiast zapisać pusty." },
    ],
    shotAlt:
      "MediaChef przed transkrypcją: pole na nagranie, w menu bocznym Modele, skąd pobiera się modele Whisper.",
    shotCaption: "Modele mieszkają w menu bocznym — pobierz raz i przepisuj offline.",
    tableTitle: "Który model Whisper wybrać",
    tableLead:
      "W katalogu są cztery modele, pobierane w aplikacji. Większy oznacza lepszy tekst i dłuższe liczenie na tej samej maszynie, więc wybieraj pod zadanie, a nie raz na zawsze.",
    tableHead: ["Model", "Pobranie", "Kiedy wybrać"],
    tableRows: [
      ["tiny", "78 MB", "Pierwsze przejście po wyraźnej mowie albo gdy trzeba tylko znaleźć, gdzie zaczyna się temat."],
      ["base", "148 MB", "Notatki dla siebie: czytelny tekst, który i tak przejrzysz i poprawisz."],
      ["small", "488 MB", "Wartość domyślna we wszystkich przepisach transkrypcji i model, przy którym większość zostaje. Wywiady, spotkania, wykłady."],
      ["large-v3-turbo", "1,62 GB", "Tekst, który pójdzie do kogoś innego: publikowane napisy, cytowane fragmenty. Zoptymalizowany pod Apple Silicon."],
    ],
    tableNote:
      "Język wykrywany jest automatycznie, można go też ustawić na sztywno. Dwa dodatkowe przepisy tłumaczą dowolny język na angielski — jako tekst albo jako napisy z czasami — w tym samym przebiegu.",
    whyTitle: "Dlaczego przepisywać u siebie",
    whyBullets: [
      { h: "Poufne nagranie zostaje poufne.", p: "Wywiady, notatki terapeutyczne, rozmowy prawne, wszystko objęte poufnością: plik czyta proces na twojej własnej maszynie i nic poza tym." },
      { h: "Bez opłaty za minutę.", p: "Transkrypcja w chmurze liczy za minutę. Lokalnie dziesiąta godzina dźwięku kosztuje tyle co pierwsza: nic." },
      { h: "Bez limitu długości i rozmiaru.", p: "Czterogodzinne nagranie to jedno zadanie w kolejce, a nie płatny plan ani obejście z dzieleniem pliku." },
      { h: "Działa całkiem bez sieci.", p: "Gdy model leży na dysku, transkrypcja jest offline: w samolocie, w laboratorium, na maszynie odciętej od sieci." },
      { h: "Napisy i tekst z jednego przebiegu.", p: "SRT i VTT niosą czasy dla odtwarzacza, TXT to czysta proza, JSON ma czasy fragmentów do twoich własnych skryptów." },
    ],
    faqTitle: "Częste pytania",
    faq: [
      { q: "Jak dokładna jest transkrypcja Whisper?", a: "Dokładność zależy od modelu: tiny to szkic, small to zrównoważona wartość domyślna, large-v3-turbo przy wyraźnej mowie zbliża się do poziomu człowieka. Najlepiej wychodzi czysty dźwięk z jednym mówcą; mocne akcenty, mówienie jeden przez drugiego i muzyka pod głosem kosztują dokładność — tak jak w każdym systemie rozpoznawania mowy." },
      { q: "Jakie języki obsługuje?", a: "Whisper obejmuje około stu języków i sam wykrywa język; można go też ustawić, jeśli trafi źle. Dwa przepisy tłumaczą mowę z każdego z nich na angielski w jednym przebiegu, jako tekst albo jako napisy SRT." },
      { q: "W jakich formatach wychodzi transkrypcja?", a: "TXT dla zwykłego tekstu, SRT i VTT ze znacznikami czasu dla odtwarzaczy i programów montażowych oraz JSON z początkiem i końcem każdego fragmentu dla skryptów i narzędzi." },
      { q: "Czy potrzebuję internetu?", a: "Raz, żeby pobrać model Whisper na ekranie Modele — od 78 MB do 1,62 GB, zależnie od wyboru. Potem transkrypcja działa całkowicie offline." },
      { q: "A jeśli w nagraniu nie ma mowy?", a: "MediaChef zgłasza „Nie wykryto mowy” zamiast zapisać pusty plik i odhaczyć zadanie na zielono. Cisza, muzyka bez wokalu i omyłkowo wybrany plik kończą się tak samo uczciwie." },
    ],
    ctaTitle: "Zamień to nagranie w tekst",
    ctaSub: `MediaChef ${FACTS.version} — Whisper lokalnie, za darmo i z otwartym kodem.`,
    also: [
      { page: "mp3", label: "Konwersja MP4 na MP3 — za darmo i offline" },
      { page: "home", label: `Wszystkie ${FACTS.recipeCount} przepisów i jak działa MediaChef` },
    ],
  },
};

export default { ui, landings };
