// Тексты локали «pt». Ориентир — бразильский португальский: там основной объём
// поиска. Структура зеркальна остальным локалям.
import { FACTS } from "../facts";

export const ui = {
  title: "MediaChef — conversor de vídeo e áudio offline com transcrição",
  description:
    "Aplicativo gratuito e de código aberto para macOS, Windows e Linux: converta vídeo e áudio no seu próprio computador e transforme fala em texto com o Whisper. Sem upload, sem limite de tamanho, sem assinatura.",
  nav: { recipes: "Receitas", transcribe: "Transcrição", privacy: "Offline", faq: "Perguntas" },
  skipToContent: "Ir para o conteúdo",
  heroTitle1: "Qualquer arquivo, em qualquer formato.",
  heroTitle2: "A fala, em texto.",
  heroAccent: "Tudo no seu computador.",
  heroSub:
    "O MediaChef é um aplicativo gratuito que transforma FFmpeg e Whisper em fichas de receita: converta vídeo e áudio, extraia o som de um clipe, passe uma gravação para texto — offline, na sua própria máquina, sem enviar nada para lugar nenhum.",
  trust: [
    `Versão ${FACTS.version}`,
    `${FACTS.recipeCount} receitas prontas`,
    `${FACTS.modelCount} modelos do Whisper`,
    "macOS · Windows · Linux",
    "Código aberto · GPL-3.0",
  ],
  ctaMac: "Baixar para macOS",
  ctaWin: "Baixar para Windows",
  ctaLinux: "Baixar para Linux",
  ctaNote: "Gratuito e de código aberto —",
  ctaNoteLink: "veja o código no GitHub",
  howTitle: "Como funciona",
  steps: [
    { n: "1", h: "Solte um arquivo", p: "Arraste um vídeo ou uma gravação. O MediaChef analisa o arquivo e mostra apenas as receitas que combinam com o que encontrou dentro." },
    { n: "2", h: "Escolha uma receita", p: "Cada ação é uma ficha simples: «Extrair áudio para MP3», «Criar legendas SRT para um vídeo», «Comprimir vídeo». Os valores padrão já são sensatos, e a prévia mostra o comando exato do FFmpeg." },
    { n: "3", h: "Pegue o resultado", p: "O arquivo aparece ao lado do original — ou na pasta que você escolher. A fila mostra o progresso, o tempo restante e onde o resultado foi parar." },
  ],
  shotAlt:
    "Tela principal do MediaChef: menu lateral com Conversão, Modelos e Configurações, uma área para soltar arquivos e a fila de tarefas à direita.",
  shotCaption:
    "A janela real, no mesmo tema em que você está lendo. A área de arquivos no centro, a fila à direita e os motores já embutidos.",
  outTitle: "O que ele faz assim que você instala",
  outLead:
    "O aplicativo vem com dezessete receitas. Cada uma é uma tarefa real do FFmpeg ou do Whisper com os parâmetros já preenchidos, e cada uma grava o resultado ao lado do seu arquivo como {nome}.{o quê}.{extensão}.",
  outHead: ["Direção", "Receita no aplicativo", "O que você recebe"],
  outRows: [
    ["Vídeo → áudio", "Extrair áudio para MP3", "<code>clip.audio.mp3</code> a 128, 192 ou 320 kbps"],
    ["Vídeo → legendas", "Criar legendas SRT para um vídeo", "<code>clip.subs.srt</code> com marcações de tempo"],
    ["Áudio → texto", "Transcrever áudio para texto", "<code>talk.transcript.txt</code>, texto simples"],
    ["Qualquer idioma → inglês", "Traduzir a fala para texto em inglês", "<code>talk.english.txt</code> em uma única passagem"],
    ["MP4 → MKV", "Converter MP4 em MKV", "Reempacotado, não recodificado — segundos e sem perda"],
    ["Vídeo → menor", "Comprimir vídeo (predefinição de qualidade)", "H.264 com CRF 23, 28 ou 33"],
    ["Vídeo → GIF", "Vídeo para GIF", "10–24 fps, largura 320–640"],
    ["Todo o resto", "Comando próprio do FFmpeg", "Seus próprios argumentos, com prévia do comando"],
  ],
  modelsTitle: "Modelos do Whisper",
  modelsLead:
    "A transcrição roda no whisper.cpp com os modelos Whisper da OpenAI. Você baixa um modelo uma vez na tela Modelos; depois disso tudo funciona com a rede desligada. Modelo maior, texto melhor, execução mais demorada.",
  modelsHead: ["Modelo", "Download", "Para que serve"],
  modelSizes: {
    tiny: "78 MB",
    base: "148 MB",
    small: "488 MB",
    "large-v3-turbo": "1,62 GB",
  },
  modelNotes: {
    tiny: "O mais rápido, qualidade aproximada. Um rascunho de fala clara numa fração do tempo.",
    base: "Rápido, qualidade razoável. Suficiente para procurar numa gravação o trecho que você quer.",
    small: "O equilíbrio recomendado — o padrão em todas as receitas de transcrição.",
    "large-v3-turbo": "A melhor qualidade, otimizado para Apple Silicon. Para texto que você vai publicar.",
  },
  defaultTag: "padrão",
  recipesTitle: "Receitas no lugar de comandos",
  recipesLead:
    "O FFmpeg faz quase tudo — no idioma do terminal. O MediaChef traduz: você escolhe o que fazer e os parâmetros já estão prontos. A prévia mostra o comando real, então você aprende no caminho.",
  recipes: [
    { tile: "tile-ochre", h: "Extrair áudio para MP3", p: "Tire a trilha sonora de qualquer vídeo." },
    { tile: "tile-green", h: "Criar legendas SRT", p: "O Whisper ouve e escreve um arquivo SRT." },
    { tile: "tile-green", h: "Comprimir vídeo", p: "Ajuste um clipe ao tamanho que o mensageiro aceita." },
    { tile: "tile-purple", h: "Vídeo para GIF", p: "Um GIF nítido em loop, de 10 a 24 fps." },
    { tile: "tile-green", h: "Transcrever áudio para texto", p: "Uma reunião ou um áudio de voz em texto simples." },
    { tile: "tile-blue", h: "Traduzir a fala para o inglês", p: "O Whisper transcreve e traduz em uma passagem." },
    { tile: "tile-blue", h: "Converter MP4 em MKV", p: "Reempacota sem recodificar — instantâneo." },
    { tile: "tile-red", h: "Remover o áudio do vídeo", p: "Elimine todas as faixas de áudio e mantenha a imagem." },
  ],
  trTitle: "Transcreva áudio para texto sem sair do seu computador",
  trBullets: [
    { h: "Whisper rodando localmente.", p: "O modelo de fala da OpenAI é executado no seu próprio processador via whisper.cpp — as gravações nunca saem da máquina." },
    { h: "Modelos baixados no aplicativo.", p: "Do tiny, de 78 MB, ao large-v3-turbo, de 1,62 GB — escolha conforme a tarefa na tela Modelos." },
    { h: "Texto ou legendas.", p: "TXT simples, SRT e VTT com marcações de tempo, ou JSON com o tempo de cada segmento para suas ferramentas." },
    { h: "Resultado honesto.", p: "Se o arquivo não tem fala, o MediaChef diz «Nenhuma fala detectada» — nunca entrega um arquivo vazio com um visto verde." },
  ],
  recipesLink: "Guia completo: converter MP4 em MP3 →",
  trLink: "Guia completo: transcrever áudio para texto →",
  privTitle: "Seus arquivos não vão a lugar nenhum",
  privLead:
    "Um conversor online pede que você envie o arquivo para o servidor de outra pessoa, espere numa fila e confie na política de retenção dela. O MediaChef trabalha na sua CPU: um gigabyte de gravação de tela e o áudio privado de uma reunião são convertidos do mesmo jeito — com o Wi-Fi desligado.",
  privChips: ["Sem upload", "Sem limite de tamanho", "Sem assinatura"],
  ossTitle: "Código aberto, motores inclusos",
  ossLead:
    "GPL-3.0, com todo o histórico de desenvolvimento público no GitHub. Desde a 0.4.0 cada download carrega seus próprios motores — nada para instalar no PATH, nada para configurar.",
  engineRows: [
    { k: `FFmpeg ${FACTS.ffmpeg}`, v: "conversão · GPL v3" },
    { k: `whisper.cpp ${FACTS.whisper}`, v: "reconhecimento de fala · MIT" },
    { k: "macOS · Windows · Linux", v: "dmg ~66 MB · instalador ~82 MB · AppImage ~181 MB · deb ~118 MB" },
  ],
  ossNotice: "Versões e licenças exatas de tudo que vem embutido — NOTICE.md",
  faqTitle: "Perguntas frequentes",
  faq: [
    { q: "É gratuito mesmo?", a: "Sim. O MediaChef é código aberto sob GPL-3.0 — sem conta, sem período de teste, sem marca d'água. O conversor e a transcrição são o aplicativo inteiro, e o código é público no GitHub." },
    { q: "Quais formatos são suportados?", a: "Tudo o que o FFmpeg lê: MP4, MKV, MOV, WebM, AVI, TS, MP3, WAV, FLAC, M4A, OGG e dezenas de outros. O MediaChef analisa o arquivo com o ffprobe em vez de confiar na extensão, então as receitas que você vê são as que realmente servem." },
    { q: "Para onde meus arquivos são enviados?", a: "Para lugar nenhum. A conversão e a transcrição rodam inteiramente no seu computador. A única coisa que o MediaChef baixa é um modelo do Whisper — uma vez, na tela Modelos." },
    { q: "Qual é a precisão da transcrição?", a: "Ela usa os modelos Whisper da OpenAI através do whisper.cpp v1.7.6. A precisão acompanha o modelo escolhido: tiny é instantâneo e aproximado, small é o equilíbrio padrão, large-v3-turbo chega perto do nível humano com fala clara. O idioma é detectado automaticamente." },
    { q: "Funciona offline?", a: "Sim. FFmpeg e Whisper vêm dentro do download, então a conversão funciona offline desde a primeira execução, e a transcrição também assim que você baixar um modelo uma vez." },
    { q: "Por que não usar um conversor online?", a: "Para um arquivo pequeno e público, um conversor online resolve. Gravações privadas, vídeos de vários gigabytes, lotes e qualquer coisa sob acordo de confidencialidade ficam melhor no computador: sem espera de upload, sem teto de tamanho e sem nada guardado no disco de outra pessoa." },
  ],
  finalTitle: "Coloque um chef no comando dos seus arquivos",
  finalSub: `Gratuito, código aberto, ${FACTS.platformCount} plataformas. Versão ${FACTS.version}.`,
  betaNote:
    "O MediaChef é novo: as compilações ainda não são assinadas pela Apple nem pela Microsoft, então a primeira execução pede confirmação — dentro de cada download há instruções em texto simples.",
  footRights: "© 2026 mediachef.app · GPL-3.0",
  footTagline: "Uma cozinha de mídia de código aberto.",
  tocLabel: "Nesta página",
  breadcrumbHome: "Início",
  alsoLabel: "Leia a seguir",
  footNavLabel: "Links do projeto",

  menu: {
    navLabel: "Site",
    menu: "Menu",
    features: "Recursos",
    guides: "Guias",
    download: "Baixar",
    faq: "Perguntas",
    gConvert: "Conversão",
    gTranscribe: "Transcrição",
    gTrust: "Privacidade e código",
    gMac: "macOS",
    gWin: "Windows",
    gLinux: "Linux",
    allFiles: "Todos os arquivos e notas da versão",
    footProduct: "Produto",
    footGuides: "Guias",
    footDownload: "Baixar",
    footProject: "Projeto",
    footBlurb: `Uma cozinha de mídia gratuita para macOS, Windows e Linux. FFmpeg ${FACTS.ffmpeg} e whisper.cpp ${FACTS.whisper} vêm dentro do download — não há nada para instalar à parte.`,
    license: "Licença GPL-3.0",
    notice: "O que vem dentro — NOTICE.md",
    sourceCode: "Código-fonte no GitHub",
    releases: "Todas as versões",
    langLabel: "Idioma",
    // Подпись на схеме окна приложения в hero.
    dropHere: "Solte os arquivos aqui",
    dlWin: "Windows · instalador",
    nApple: "Apple Silicon",
    nZip: "Apple Silicon, sem instalador",
    nWin: "64 bits",
    nAppimage: "x86_64, roda como está",
    nDeb: "x86_64, Debian e Ubuntu",
    sHow: "Como funciona",
    sRecipes: "Receitas",
    sOut: "O que ele faz de imediato",
    sTranscribe: "Transcrição",
    sModels: "Modelos do Whisper",
    sPrivacy: "Offline e privado",
    sOss: "Código aberto",
    sFaq: "Perguntas",
    pMp3: "MP4 em MP3",
    pTranscribe: "Áudio em texto",
  },
};

export const landings = {
  mp3: {
    title: "Converter MP4 em MP3 grátis e offline — MediaChef",
    description:
      "Extraia o áudio de um MP4 e salve como MP3 no seu próprio computador: sem upload, sem teto de tamanho, sem marca d'água. Aplicativo gratuito e de código aberto para macOS, Windows e Linux.",
    h1: "Converter MP4 em MP3 — grátis, offline, no seu computador",
    crumb: "MP4 em MP3",
    lead:
      "O MediaChef traz uma receita chamada «Extrair áudio para MP3». Solte um vídeo na área de arquivos, escolha um bitrate e clique em iniciar: a trilha sonora é gravada ao lado do original como MP3. O arquivo nunca sai da sua máquina, não há limite de tamanho e tudo funciona com a rede desligada.",
    sections: { how: "how", table: "bitrate", why: "offline", faq: "faq" },
    toc: ["Como converter MP4 em MP3", "Qual bitrate escolher", "Por que converter no seu computador", "Perguntas"],
    stepsTitle: "Como converter MP4 em MP3",
    steps: [
      { h: "Baixe o MediaChef", p: "Um arquivo para macOS, Windows ou Linux. O FFmpeg já vem dentro — nada para instalar à parte, nada para adicionar ao PATH." },
      { h: "Solte o MP4 na área de arquivos", p: "O MediaChef lê o arquivo com o ffprobe e mantém apenas as receitas que servem. Um vídeo com faixa de áudio recebe a ficha do MP3 na hora." },
      { h: "Escolha «Extrair áudio para MP3»", p: "Selecione o bitrate: 128k para fala, 192k como padrão, 320k para arquivamento. A prévia do comando se atualiza conforme você troca." },
      { h: "Clique em iniciar e pegue o arquivo", p: "O MP3 aparece ao lado do vídeo como clip.audio.mp3. A fila mostra o progresso, o tempo restante e o caminho final." },
    ],
    shotAlt:
      "MediaChef pronto para converter MP4 em MP3: a área de arquivos esperando um vídeo, com a fila de tarefas à direita.",
    shotCaption: "A área onde o MP4 entra. As receitas aparecem assim que o MediaChef lê o arquivo.",
    tableTitle: "Qual bitrate escolher",
    tableLead:
      "A receita oferece três bitrates. Os tamanhos abaixo são para uma hora de áudio — é aritmética do bitrate, então uma gravação de duas horas simplesmente pesa o dobro.",
    tableHead: ["Bitrate", "Uma hora de áudio", "Escolha quando"],
    tableRows: [
      ["128 kbps", "≈ 58 MB", "Fala: entrevistas, podcasts, aulas, áudios de voz. O menor arquivo, sem perda audível numa voz."],
      ["192 kbps", "≈ 86 MB", "O padrão. Música que você realmente escuta, e qualquer coisa sobre a qual esteja em dúvida."],
      ["320 kbps", "≈ 144 MB", "Arquivamento, ou áudio que você vai editar mais e recodificar de novo depois."],
    ],
    tableNote:
      "Não só MP4: a mesma receita aparece para MKV, MOV, WebM, AVI, TS e qualquer outra coisa que o FFmpeg consiga ler, desde que o arquivo tenha faixa de áudio.",
    whyTitle: "Por que converter no seu computador",
    whyBullets: [
      { h: "Nada é enviado.", p: "Uma chamada gravada ou um corte ainda não publicado fica no seu disco. Não existe cópia em servidor cuja política de retenção você precise acreditar." },
      { h: "Sem teto de tamanho.", p: "Conversores online param entre 100 MB e 2 GB e colocam você numa fila. Uma gravação de tela de quatro gigabytes converte igual a uma de quatro megabytes." },
      { h: "Mais rápido com arquivos reais.", p: "Extrair uma faixa de áudio que já existe é rápido. O lento é enviar o vídeo antes — e localmente essa parte não existe." },
      { h: "Grátis e sem conta.", p: "Código aberto GPL-3.0: sem cadastro, sem teste, sem marca d'água, sem limite por arquivo." },
      { h: "Em lote, não um por vez.", p: "Solte todos os clipes de uma vez; a fila processa e diz onde cada MP3 foi parar." },
    ],
    faqTitle: "Perguntas frequentes",
    faq: [
      { q: "Converter MP4 em MP3 perde qualidade?", a: "MP3 é um formato com perdas, então a faixa é recodificada uma vez. Nos 192 kbps padrão isso é inaudível em fala e muito próximo disso em música. Se o arquivo é um master com o qual você ainda vai trabalhar, use 320 kbps." },
      { q: "Qual o maior arquivo que posso converter?", a: "O MediaChef não impõe limite — o limite é o seu espaço livre em disco, e o aplicativo confere antes de começar. A duração também não importa: uma gravação de três horas é uma única tarefa na fila." },
      { q: "Funciona sem internet?", a: "Sim, completamente. O FFmpeg vem dentro do download, então a conversão nunca toca a rede. Só a transcrição precisa baixar um modelo uma vez." },
      { q: "Posso converter vários vídeos de uma vez?", a: "Pode. Solte todos na área de arquivos, adicione a receita e a fila executa um após o outro, com progresso e tempo restante para cada um." },
      { q: "Tem marca d'água ou versão paga?", a: "Não. O MediaChef é código aberto GPL-3.0 sem nenhuma versão paga, e não mexe no seu áudio além da conversão que você pediu." },
      { q: "Se eu transformar um MP4 em MP3, o vídeo original continua lá?", a: "Sim. O MediaChef lê o vídeo e grava um MP3 novo ao lado: o MP4 não é sobrescrito, renomeado nem apagado, então dá para passar o mesmo arquivo para áudio quantas vezes quiser. Nada é enviado para lugar nenhum, tudo roda sem conexão." },
    ],
    ctaTitle: "Tire o MP3 desse vídeo",
    ctaSub: `MediaChef ${FACTS.version} — grátis, código aberto, macOS · Windows · Linux.`,
    also: [
      { page: "transcribe", label: "Transcrever áudio para texto — offline, com o Whisper" },
      { page: "home", label: `As ${FACTS.recipeCount} receitas e como o MediaChef funciona` },
    ],
  },
  transcribe: {
    title: "Transcrever áudio para texto offline com o Whisper — MediaChef",
    description:
      "Transforme gravações em texto no seu próprio computador com o Whisper: TXT, SRT, VTT ou JSON. Sem upload, sem cobrança por minuto, sem limite de duração. Aplicativo gratuito para macOS, Windows e Linux.",
    h1: "Transcrever áudio para texto — offline, no seu próprio computador",
    crumb: "Áudio em texto",
    lead:
      "O MediaChef roda o Whisper da OpenAI localmente através do whisper.cpp. Baixe um modelo uma vez, solte uma gravação ou um vídeo na área de arquivos e escolha o que quer de saída: texto simples, legendas SRT ou VTT com tempos, ou JSON com o tempo de cada segmento. O áudio nunca é enviado e não há preço por minuto.",
    sections: { how: "how", table: "models", why: "offline", faq: "faq" },
    toc: ["Como transcrever uma gravação", "Qual modelo do Whisper escolher", "Por que transcrever no seu computador", "Perguntas"],
    outLabel: "O que você recebe",
    outSample: "00:00:04  Oi, pessoal, vamos começar…\n00:00:11  Primeiro ponto: os planos do trimestre.\n00:00:19  São três cenários, vou mostrar a tabela.",
    outNote: "TXT sem tempos, SRT e VTT com eles, JSON com o início e o fim de cada segmento.",
    stepsTitle: "Como transcrever uma gravação",
    steps: [
      { h: "Baixe o MediaChef", p: "Um arquivo para macOS, Windows ou Linux. O whisper.cpp v1.7.6 já vem dentro do download; só o modelo é baixado à parte." },
      { h: "Escolha um modelo do Whisper", p: "Abra Modelos e baixe um — small (488 MB) é o equilíbrio padrão. Baixa uma vez; depois a transcrição funciona com a rede desligada." },
      { h: "Solte a gravação ou o vídeo", p: "Áudio e vídeo funcionam igual: o MediaChef extrai o som do vídeo sozinho, então a gravação de uma reunião e um MP4 seguem o mesmo caminho." },
      { h: "Escolha a saída que precisa", p: "«Transcrever áudio para texto» para TXT, «Transcrever áudio para legendas SRT» ou «Transcrever áudio para WebVTT» para legendas com tempos, «Transcrever áudio para JSON com tempos» para ferramentas." },
      { h: "Clique em iniciar e leia o resultado", p: "O texto aparece ao lado do arquivo como talk.transcript.txt. A fila mostra o progresso; se não houver fala no arquivo, o MediaChef avisa em vez de gravar um vazio." },
    ],
    shotAlt:
      "MediaChef antes da transcrição: a área para soltar uma gravação, com Modelos no menu lateral, de onde os modelos do Whisper são baixados.",
    shotCaption: "Os modelos ficam no menu lateral — baixe uma vez e transcreva offline daí em diante.",
    tableTitle: "Qual modelo do Whisper escolher",
    tableLead:
      "O catálogo traz quatro modelos, baixados dentro do aplicativo. Maior significa texto melhor e execução mais longa na mesma máquina, então escolha por tarefa, e não de uma vez para sempre.",
    tableHead: ["Modelo", "Download", "Quando escolher"],
    tableRows: [
      ["tiny", "78 MB", "Uma primeira passada em fala clara, ou quando você só precisa achar onde um assunto começa."],
      ["base", "148 MB", "Anotações para você mesmo: texto legível que vai reler e editar de qualquer forma."],
      ["small", "488 MB", "O padrão em todas as receitas de transcrição, e o que a maioria mantém. Entrevistas, reuniões, aulas."],
      ["large-v3-turbo", "1,62 GB", "Texto que vai para outra pessoa: legendas que você publica, citações que reproduz. Otimizado para Apple Silicon."],
    ],
    tableNote:
      "O idioma é detectado automaticamente, e você também pode fixá-lo. Duas receitas extras traduzem qualquer idioma para o inglês — como texto ou como legendas com tempos — na mesma passagem.",
    whyTitle: "Por que transcrever no seu computador",
    whyBullets: [
      { h: "Áudio confidencial continua confidencial.", p: "Entrevistas, anotações clínicas, ligações jurídicas, qualquer coisa sob acordo de confidencialidade: o arquivo é lido por um processo da sua própria máquina e por mais nada." },
      { h: "Sem cobrança por minuto.", p: "A transcrição na nuvem cobra por minuto. No computador, a décima hora de áudio custa o mesmo que a primeira: nada." },
      { h: "Sem limite de duração ou tamanho.", p: "Uma gravação de quatro horas é uma tarefa na fila, não um plano pago nem uma gambiarra de dividir o arquivo." },
      { h: "Funciona sem rede nenhuma.", p: "Com o modelo em disco, a transcrição é offline: num avião, num laboratório, numa máquina isolada." },
      { h: "Legendas e texto da mesma passagem.", p: "SRT e VTT carregam os tempos para um player, TXT é prosa limpa, JSON traz os tempos dos segmentos para os seus próprios scripts." },
    ],
    faqTitle: "Perguntas frequentes",
    faq: [
      { q: "Qual a precisão da transcrição do Whisper?", a: "A precisão acompanha o modelo: tiny é um rascunho, small é o equilíbrio padrão, large-v3-turbo chega perto do nível humano com fala clara. Áudio limpo de um único falante sai melhor; sotaques fortes, pessoas falando por cima e música sob a voz custam precisão — como em qualquer reconhecedor de fala." },
      { q: "Quais idiomas ele atende?", a: "O Whisper cobre cerca de cem idiomas e detecta o idioma sozinho; você também pode fixá-lo se o palpite estiver errado. Duas receitas traduzem a fala em qualquer um deles para o inglês numa única passagem, como texto ou como legendas SRT." },
      { q: "Em que formatos sai a transcrição?", a: "TXT para texto simples, SRT e VTT com marcações de tempo para players e editores de vídeo, e JSON com o início e o fim de cada segmento para scripts e ferramentas." },
      { q: "Preciso de internet?", a: "Uma vez, para baixar um modelo do Whisper na tela Modelos — de 78 MB a 1,62 GB, conforme o escolhido. Depois disso a transcrição roda inteiramente offline." },
      { q: "E se a gravação não tiver fala?", a: "O MediaChef informa «Nenhuma fala detectada» em vez de gravar um arquivo vazio e marcar a tarefa como concluída. Silêncio, música sem vocais e um arquivo escolhido por engano terminam com a mesma honestidade." },
      { q: "Posso transformar um vídeo em texto ou só áudio?", a: "Vídeo funciona igual. O MediaChef tira o som do próprio arquivo, então um MP4, MKV ou MOV vai direto para a transcrição: existe até uma receita separada, «Tirar o texto de um vídeo». Não precisa converter para áudio antes." },
    ],
    ctaTitle: "Transforme essa gravação em texto",
    ctaSub: `MediaChef ${FACTS.version} — Whisper rodando localmente, grátis e de código aberto.`,
    also: [
      { page: "mp3", label: "Converter MP4 em MP3 — grátis e offline" },
      { page: "home", label: `As ${FACTS.recipeCount} receitas e como o MediaChef funciona` },
    ],
  },
};

export default { ui, landings };
