// Тексты локали «zh» (упрощённый китайский). Структура зеркальна остальным.
import { FACTS } from "../facts";

export const ui = {
  title: "MediaChef — 离线视频音频转换器，带语音转文字",
  description:
    "面向 macOS、Windows 和 Linux 的免费开源应用：在自己的电脑上转换视频和音频，并用 Whisper 把语音转成文字。无需上传、没有体积上限、不用订阅。",
  nav: { recipes: "配方", transcribe: "语音转文字", privacy: "离线", faq: "常见问题" },
  skipToContent: "跳到正文",
  heroTitle1: "任何文件，转成任何格式。",
  heroTitle2: "语音，转成文字。",
  heroAccent: "全部在你的电脑上完成。",
  heroSub:
    "MediaChef 是一款免费应用，它把 FFmpeg 和 Whisper 变成一张张配方卡：转换视频和音频、从片段中提取声音、把录音转成文字——离线运行，在你自己的机器上，不向任何地方上传。",
  trust: [
    `版本 ${FACTS.version}`,
    `内置 ${FACTS.recipeCount} 个配方`,
    `${FACTS.modelCount} 个 Whisper 模型`,
    "macOS · Windows · Linux",
    "开源 · GPL-3.0",
  ],
  ctaMac: "下载 macOS 版",
  ctaWin: "下载 Windows 版",
  ctaLinux: "下载 Linux 版",
  ctaNote: "免费且开源——",
  ctaNoteLink: "在 GitHub 上查看代码",
  howTitle: "它是怎么工作的",
  steps: [
    { n: "1", h: "放入文件", p: "把视频或录音拖进来。MediaChef 会读取文件内容，只显示与之匹配的配方。" },
    { n: "2", h: "选择配方", p: "每个操作都是一张简单的卡片：「提取音频为 MP3」「为视频生成 SRT 字幕」「压缩视频」。默认参数已经调好，预览会显示确切的 FFmpeg 命令。" },
    { n: "3", h: "取走结果", p: "文件会出现在原文件旁边——或你指定的文件夹里。队列显示进度、剩余时间和结果所在的位置。" },
  ],
  shotAlt:
    "MediaChef 主界面：侧边栏包含转换、模型和设置，中间是文件投放区，右侧是任务队列。",
  shotCaption:
    "真实窗口，配色与你此刻阅读的主题一致。中间是文件投放区，右侧是队列，引擎已经内置其中。",
  outTitle: "装好就能做的事",
  outLead:
    "应用内置十七个配方。每一个都是参数已经填好的真实 FFmpeg 或 Whisper 任务，结果按 {文件名}.{做了什么}.{扩展名} 写在你的文件旁边。",
  outHead: ["方向", "应用中的配方", "你会得到"],
  outRows: [
    ["视频 → 音频", "提取音频为 MP3", "<code>clip.audio.mp3</code>，128、192 或 320 kbps"],
    ["视频 → 字幕", "为视频生成 SRT 字幕", "<code>clip.subs.srt</code>，带时间轴"],
    ["音频 → 文字", "把音频转成文字", "<code>talk.transcript.txt</code>，纯文本"],
    ["任意语言 → 英文", "把语音翻译成英文文字", "<code>talk.english.txt</code>，一次完成"],
    ["MP4 → MKV", "把 MP4 转成 MKV", "重新封装而非重新编码——几秒钟，无损"],
    ["视频 → 更小", "压缩视频（质量预设）", "H.264，CRF 23、28 或 33"],
    ["视频 → GIF", "视频转 GIF", "10–24 fps，宽度 320–640"],
    ["其他一切", "自定义 FFmpeg 命令", "你自己的参数，附命令预览"],
  ],
  modelsTitle: "Whisper 模型",
  modelsLead:
    "语音转文字基于 whisper.cpp 与 OpenAI 的 Whisper 模型。你在「模型」界面下载一次模型，之后断网也能用。模型越大，文字越准，耗时也越长。",
  modelsHead: ["模型", "下载体积", "适合什么"],
  modelSizes: {
    tiny: "78 MB",
    base: "148 MB",
    small: "488 MB",
    "large-v3-turbo": "1.62 GB",
  },
  modelNotes: {
    tiny: "最快，质量粗糙。用极短的时间给清晰语音出一份草稿。",
    base: "速度快，质量尚可。足够在录音里找到你需要的那一段。",
    small: "推荐的平衡点——所有语音转文字配方的默认值。",
    "large-v3-turbo": "质量最好，针对 Apple Silicon 优化。适合准备发布的文字。",
  },
  defaultTag: "默认",
  recipesTitle: "用配方代替命令",
  recipesLead:
    "FFmpeg 几乎什么都能做——只是用终端的语言。MediaChef 负责翻译：你挑要做什么，参数已经设好。预览会显示真实命令，顺带就学会了。",
  recipes: [
    { tile: "tile-ochre", h: "提取音频为 MP3", p: "把任意视频里的声音轨取出来。" },
    { tile: "tile-green", h: "生成 SRT 字幕", p: "Whisper 听完后写出一个 SRT 文件。" },
    { tile: "tile-green", h: "压缩视频", p: "把片段压到聊天软件能接受的体积。" },
    { tile: "tile-purple", h: "视频转 GIF", p: "清晰的循环 GIF，10 到 24 fps。" },
    { tile: "tile-green", h: "把音频转成文字", p: "会议录音或语音消息变成纯文本。" },
    { tile: "tile-blue", h: "把语音翻译成英文", p: "Whisper 一次完成转写和翻译。" },
    { tile: "tile-blue", h: "把 MP4 转成 MKV", p: "重新封装，不重新编码——瞬间完成。" },
    { tile: "tile-red", h: "去掉视频里的声音", p: "删除全部音轨，只保留画面。" },
  ],
  trTitle: "不离开自己的电脑，把音频转成文字",
  trBullets: [
    { h: "Whisper 在本地运行。", p: "OpenAI 的语音模型通过 whisper.cpp 在你自己的处理器上执行——录音从不离开这台机器。" },
    { h: "模型在应用内下载。", p: "从 78 MB 的 tiny 到 1.62 GB 的 large-v3-turbo——在「模型」界面按任务挑选。" },
    { h: "文字或字幕。", p: "纯 TXT、带时间轴的 SRT 和 VTT，或带每段起止时间的 JSON，供你的工具使用。" },
    { h: "结果如实。", p: "如果文件里没有语音，MediaChef 会直说「未检测到语音」——绝不会交出一个打着绿勾的空文件。" },
  ],
  recipesLink: "完整指南：把 MP4 转成 MP3 →",
  trLink: "完整指南：把音频转成文字 →",
  privTitle: "你的文件哪儿也不去",
  privLead:
    "在线转换器要你把文件上传到别人的服务器、排队等待，还要相信对方的保留政策。MediaChef 在你的处理器上干活：一 GB 的录屏和一段私密会议录音，处理方式完全一样——关掉 Wi-Fi 也照样跑。",
  privChips: ["不上传", "无体积上限", "不用订阅"],
  ossTitle: "开源，引擎随包附带",
  ossLead:
    "GPL-3.0 许可，全部开发历史在 GitHub 上公开。从 0.4.0 起，每个下载都自带引擎——不用往 PATH 里装东西，也没有要配置的。",
  engineRows: [
    { k: `FFmpeg ${FACTS.ffmpeg}`, v: "转换 · GPL v3" },
    { k: `whisper.cpp ${FACTS.whisper}`, v: "语音识别 · MIT" },
    { k: "macOS · Windows · Linux", v: "dmg 约 66 MB · 安装包约 82 MB · AppImage 约 181 MB · deb 约 118 MB" },
  ],
  ossNotice: "所有内置组件的确切版本与许可 — NOTICE.md",
  faqTitle: "常见问题",
  faq: [
    { q: "真的免费吗？", a: "是的。MediaChef 采用 GPL-3.0 开源许可——不用注册、没有试用期、没有水印。转换器和语音转文字就是应用的全部，代码在 GitHub 上公开。" },
    { q: "支持哪些格式？", a: "FFmpeg 能读的都支持：MP4、MKV、MOV、WebM、AVI、TS、MP3、WAV、FLAC、M4A、OGG 以及其他几十种。MediaChef 用 ffprobe 检查文件本身，而不是相信扩展名，所以你看到的配方都是真正合适的。" },
    { q: "我的文件会上传到哪里？", a: "哪里也不会。转换和语音转文字完全在你的电脑上运行。MediaChef 唯一会下载的东西是 Whisper 模型——一次，在「模型」界面。" },
    { q: "语音转文字有多准？", a: "它通过 whisper.cpp v1.7.6 使用 OpenAI 的 Whisper 模型。准确度取决于你选的模型：tiny 立刻出结果但比较粗糙，small 是均衡的默认值，large-v3-turbo 在语音清晰时接近人工水平。语言会自动识别。" },
    { q: "离线能用吗？", a: "能。FFmpeg 和 Whisper 都在下载包内，所以从第一次启动起转换就能离线运行；只要下载过一次模型，语音转文字同样离线可用。" },
    { q: "为什么不直接用在线转换器？", a: "如果只是一个小的公开文件，在线转换器完全够用。但私密录音、几 GB 的视频、批量处理，以及任何受保密协议约束的内容，都更适合在本地做：不用等上传、没有体积上限，也不会有东西留在别人的硬盘上。" },
  ],
  finalTitle: "让主厨来打理你的媒体文件",
  finalSub: `免费、开源、支持 ${FACTS.platformCount} 个平台。版本 ${FACTS.version}。`,
  betaNote:
    "MediaChef 还很年轻：安装包尚未由 Apple 或 Microsoft 签名，因此首次启动会要求确认——每个下载包里都附有纯文本说明。",
  footRights: "© 2026 mediachef.app · GPL-3.0",
  footTagline: "一间开源的媒体厨房。",
  tocLabel: "本页内容",
  breadcrumbHome: "首页",
  alsoLabel: "接着读",
  footNavLabel: "项目链接",

  menu: {
    navLabel: "站点",
    menu: "菜单",
    features: "功能",
    guides: "指南",
    download: "下载",
    faq: "常见问题",
    gConvert: "转换",
    gTranscribe: "语音转文字",
    gTrust: "隐私与代码",
    gMac: "macOS",
    gWin: "Windows",
    gLinux: "Linux",
    allFiles: "全部文件与版本说明",
    footProduct: "产品",
    footGuides: "指南",
    footDownload: "下载",
    footProject: "项目",
    footBlurb: `面向 macOS、Windows 和 Linux 的免费媒体厨房。FFmpeg ${FACTS.ffmpeg} 和 whisper.cpp ${FACTS.whisper} 都在下载包内——不需要另外安装任何东西。`,
    license: "许可证 GPL-3.0",
    notice: "包里有什么 — NOTICE.md",
    sourceCode: "GitHub 上的源代码",
    releases: "全部版本",
    langLabel: "语言",
    // Подпись на схеме окна приложения в hero.
    dropHere: "把文件拖到这里",
    dlWin: "Windows · 安装包",
    nApple: "Apple Silicon",
    nZip: "Apple Silicon，免安装",
    nWin: "64 位",
    nAppimage: "x86_64，直接运行",
    nDeb: "x86_64，适用于 Debian 和 Ubuntu",
    sHow: "它是怎么工作的",
    sRecipes: "配方",
    sOut: "装好就能做的事",
    sTranscribe: "语音转文字",
    sModels: "Whisper 模型",
    sPrivacy: "离线且私密",
    sOss: "开源",
    sFaq: "常见问题",
    pMp3: "MP4 转 MP3",
    pTranscribe: "音频转文字",
  },
};

export const landings = {
  mp3: {
    title: "免费离线把 MP4 转成 MP3 — MediaChef",
    description:
      "在自己的电脑上从 MP4 里提取音频并保存为 MP3：不用上传、没有体积上限、没有水印。面向 macOS、Windows 和 Linux 的免费开源应用。",
    h1: "把 MP4 转成 MP3 — 免费、离线、在你的电脑上",
    crumb: "MP4 转 MP3",
    lead:
      "MediaChef 内置一个叫「提取音频为 MP3」的配方。把视频放进投放区，挑一个码率，按下开始：声音轨就会以 MP3 的形式写在原文件旁边。文件从不离开你的机器，没有体积上限，整个过程断网也能完成。",
    sections: { how: "how", table: "bitrate", why: "offline", faq: "faq" },
    toc: ["怎么把 MP4 转成 MP3", "该选哪个码率", "为什么在自己的电脑上转", "常见问题"],
    stepsTitle: "怎么把 MP4 转成 MP3",
    steps: [
      { h: "下载 MediaChef", p: "macOS、Windows 或 Linux 各一个文件。FFmpeg 已经在里面——不用另外安装，也不用往 PATH 里加东西。" },
      { h: "把 MP4 放进投放区", p: "MediaChef 用 ffprobe 读取文件，只保留合适的配方。带音轨的视频会立刻出现 MP3 卡片。" },
      { h: "选择「提取音频为 MP3」", p: "挑码率：语音用 128k，默认 192k，存档用 320k。切换时命令预览会跟着更新。" },
      { h: "按下开始并取走文件", p: "MP3 会以 clip.audio.mp3 的名字出现在视频旁边。队列显示进度、剩余时间和最终路径。" },
    ],
    shotAlt:
      "MediaChef 准备把 MP4 转成 MP3：投放区正等待视频文件，右侧是任务队列。",
    shotCaption: "MP4 放进去的地方。MediaChef 读完文件后，配方就会出现。",
    tableTitle: "该选哪个码率",
    tableLead:
      "这个配方提供三种码率。下表的体积按一小时音频计算——这是从码率直接算出来的，所以两小时的录音就是两倍。",
    tableHead: ["码率", "一小时音频", "什么时候选它"],
    tableRows: [
      ["128 kbps", "≈ 58 MB", "语音：访谈、播客、讲座、语音备忘。文件最小，人声听不出损失。"],
      ["192 kbps", "≈ 86 MB", "默认值。你真的会听的音乐，以及任何拿不准的情况。"],
      ["320 kbps", "≈ 144 MB", "存档，或者之后还要继续剪辑、再次编码的音频。"],
    ],
    tableNote:
      "不只是 MP4：只要文件里有音轨，同一个配方也会出现在 MKV、MOV、WebM、AVI、TS 以及 FFmpeg 能读的其他格式上。",
    whyTitle: "为什么在自己的电脑上转",
    whyBullets: [
      { h: "什么都不上传。", p: "录下来的通话或还没发布的剪辑留在你的硬盘上。不存在需要你相信其保留政策的服务器副本。" },
      { h: "没有体积上限。", p: "在线转换器在 100 MB 到 2 GB 之间就停下并让你排队。四 GB 的录屏和四 MB 的片段转起来是一样的。" },
      { h: "对真实文件更快。", p: "提取一条已经存在的音轨很快。慢的是先把视频传上去——而在本地根本没有这一步。" },
      { h: "免费，不用注册。", p: "GPL-3.0 开源：不注册、无试用、无水印、单个文件没有限制。" },
      { h: "成批处理，而不是一个一个来。", p: "把所有片段一次放进去；队列会逐个处理，并告诉你每个 MP3 落在哪里。" },
    ],
    faqTitle: "常见问题",
    faq: [
      { q: "MP4 转 MP3 会损失质量吗？", a: "MP3 是有损格式，所以音轨会被重新编码一次。在默认的 192 kbps 下，语音听不出差别，音乐也非常接近。如果这个文件是你还要继续加工的母版，就选 320 kbps。" },
      { q: "最大能转多大的文件？", a: "MediaChef 不设上限——上限是你的磁盘剩余空间，应用会在开始前检查。时长也不影响：三小时的录音只是队列里的一个任务。" },
      { q: "没有网络能用吗？", a: "完全可以。FFmpeg 就在下载包内，转换过程从不接触网络。只有语音转文字需要一次性下载模型。" },
      { q: "能一次转好几个视频吗？", a: "可以。把它们全部放进投放区，加上配方，队列就会逐个执行，每个都有进度和剩余时间。" },
      { q: "有水印或付费版吗？", a: "没有。MediaChef 是 GPL-3.0 开源软件，完全没有付费版，除了你要求的转换之外不会动你的音频。" },
      { q: "把 MP4 转为 MP3 之后，原来的视频还在吗？", a: "还在。MediaChef 读取视频后会在旁边写一个新的 MP3 文件，原来的 MP4 不会被覆盖、改名或删除，所以同一个文件想转成音频多少次都可以。也不会上传任何东西，整个过程无需联网。" },
    ],
    ctaTitle: "把那段视频里的 MP3 取出来",
    ctaSub: `MediaChef ${FACTS.version} — 免费、开源，macOS · Windows · Linux。`,
    also: [
      { page: "transcribe", label: "把音频转成文字 — 离线，用 Whisper" },
      { page: "home", label: `全部 ${FACTS.recipeCount} 个配方与 MediaChef 的工作方式` },
    ],
  },
  transcribe: {
    title: "用 Whisper 离线把音频转成文字 — MediaChef",
    description:
      "在自己的电脑上用 Whisper 把录音变成文字：TXT、SRT、VTT 或 JSON。不用上传、不按分钟计费、没有时长限制。面向 macOS、Windows 和 Linux 的免费应用。",
    h1: "把音频转成文字 — 离线，在你自己的电脑上",
    crumb: "音频转文字",
    lead:
      "MediaChef 通过 whisper.cpp 在本地运行 OpenAI 的 Whisper。下载一次模型，然后把录音或视频放进投放区，挑你要的输出：纯文本、带时间轴的 SRT 或 VTT 字幕，或者带每段起止时间的 JSON。音频从不上传，也没有按分钟计费。",
    sections: { how: "how", table: "models", why: "offline", faq: "faq" },
    toc: ["怎么转写一段录音", "该选哪个 Whisper 模型", "为什么在自己的电脑上转写", "常见问题"],
    outLabel: "你会得到什么",
    outSample: "00:00:04  大家好，我们开始吧……\n00:00:11  第一项：本季度的计划。\n00:00:19  有三种方案，我把表格调出来。",
    outNote: "TXT 不带时间，SRT 和 VTT 带时间，JSON 里有每一段的起止时间。",
    stepsTitle: "怎么转写一段录音",
    steps: [
      { h: "下载 MediaChef", p: "macOS、Windows 或 Linux 各一个文件。whisper.cpp v1.7.6 已经在下载包内；只有模型是单独下载的。" },
      { h: "选一个 Whisper 模型", p: "打开「模型」下载一个——small（488 MB）是均衡的默认选择。下载一次之后，断网也能转写。" },
      { h: "放入录音或视频", p: "音频和视频都行：MediaChef 会自己从视频里取出声音，所以会议录音和 MP4 走的是同一条路。" },
      { h: "选择你要的输出", p: "要 TXT 就用「把音频转成文字」，要带时间轴的字幕就用「把音频转成 SRT 字幕」或「把音频转成 WebVTT」，给工具用就选「把音频转成带时间的 JSON」。" },
      { h: "按下开始并读结果", p: "文字会以 talk.transcript.txt 的名字落在文件旁边。队列显示进度；如果文件里没有语音，MediaChef 会直说，而不是写出一个空文件。" },
    ],
    shotAlt:
      "转写前的 MediaChef：录音的投放区，侧边栏里是「模型」，Whisper 模型从那里下载。",
    shotCaption: "模型放在侧边栏里——下载一次，之后就离线转写。",
    tableTitle: "该选哪个 Whisper 模型",
    tableLead:
      "目录里有四个模型，在应用内下载。模型越大，文字越好，同一台机器上耗时也越长，所以按任务来挑，而不是一次定终身。",
    tableHead: ["模型", "下载体积", "什么时候选它"],
    tableRows: [
      ["tiny", "78 MB", "对清晰语音做第一遍，或者你只需要找到某个话题从哪里开始。"],
      ["base", "148 MB", "给自己看的笔记：反正你都会再扫一遍并修改的可读文字。"],
      ["small", "488 MB", "所有转写配方的默认值，也是多数人最后留下的那个。访谈、会议、讲座。"],
      ["large-v3-turbo", "1.62 GB", "要给别人看的文字：你会发布的字幕、你会引用的原话。针对 Apple Silicon 优化。"],
    ],
    tableNote:
      "语言会自动识别，你也可以固定它。另有两个配方能把任意语言在同一遍里翻译成英文——输出文字或带时间轴的字幕。",
    whyTitle: "为什么在自己的电脑上转写",
    whyBullets: [
      { h: "机密音频依然机密。", p: "访谈、诊疗记录、法律通话，以及任何受保密协议约束的内容：读取文件的只是你自己机器上的一个进程，除此之外没有别的。" },
      { h: "不按分钟计费。", p: "云端转写按分钟收费。在本地，第十个小时的音频和第一个小时一样：不要钱。" },
      { h: "没有时长和体积限制。", p: "四小时的录音就是队列里的一个任务，既不是付费档位，也不用把文件切开将就。" },
      { h: "完全不需要网络。", p: "模型落到硬盘上之后，转写就是离线的：在飞机上、在实验室里、在与网络隔离的机器上都行。" },
      { h: "字幕和文字一遍出。", p: "SRT 和 VTT 带着给播放器用的时间轴，TXT 是干净的正文，JSON 里有分段时间供你自己的脚本使用。" },
    ],
    faqTitle: "常见问题",
    faq: [
      { q: "Whisper 转写有多准？", a: "准确度取决于模型：tiny 是草稿，small 是均衡的默认值，large-v3-turbo 在语音清晰时接近人工水平。单人、干净的音频效果最好；口音很重、多人抢话、人声下面压着音乐都会拉低准确度——任何语音识别系统都是如此。" },
      { q: "支持哪些语言？", a: "Whisper 覆盖约一百种语言并会自行识别语种；如果识别错了，你也可以手动固定。有两个配方能把其中任意一种语言的语音一遍翻译成英文，输出文字或 SRT 字幕。" },
      { q: "转写结果有哪些格式？", a: "纯文本用 TXT，给播放器和剪辑软件用的是带时间轴的 SRT 和 VTT，给脚本和工具用的是带每段起止时间的 JSON。" },
      { q: "需要联网吗？", a: "需要一次，在「模型」界面下载一个 Whisper 模型——按你选的不同，从 78 MB 到 1.62 GB。之后转写完全离线运行。" },
      { q: "如果录音里没有语音怎么办？", a: "MediaChef 会报告「未检测到语音」，而不是写出一个空文件再给任务打上绿勾。静音、没有人声的音乐、以及选错的文件，结局同样如实。" },
      { q: "可以把视频转为文字吗，还是只能音频？", a: "视频一样可以。MediaChef 会直接从文件里提取声音，所以 MP4、MKV、MOV 都能直接转文字，还有一个单独的菜谱「从视频里取出文字」。不必先把视频转换成音频。" },
    ],
    ctaTitle: "把那段录音变成文字",
    ctaSub: `MediaChef ${FACTS.version} — Whisper 本地运行，免费且开源。`,
    also: [
      { page: "mp3", label: "把 MP4 转成 MP3 — 免费且离线" },
      { page: "home", label: `全部 ${FACTS.recipeCount} 个配方与 MediaChef 的工作方式` },
    ],
  },
};

export default { ui, landings };
